Profile: JP_ImagingStudy_Pathology
Parent: ImagingStudy
Id: jp-imagingstudy-pathology
Title: "JP Core ImagingStudy Pathology Profile"
Description: "このプロファイルはImagingStudyリソースに対して、病理WSIのDICOM画像に関するデータを送受信するための制約と拡張を定めたものである。"
* ^url = "http://jpfhir.jp/fhir/core/StructureDefinition/JP_ImagingStudy_Pathology"
* ^status = #active
* ^version = "1.0.0"
* . ^short = "病理WSIのDICOM画像に関する情報。"
* . ^definition = "病理WSIのDICOM画像に関する情報。"
* identifier ^short = "DICOM画像全体を一意に識別するためのID【詳細参照】"
* identifier ^definition = "DICOM画像全体を一意に識別するためのID。"
* identifier ^comment = "Study Instance UIDの値を指定する。"
* status ^short = "DICOM画像のステータス【詳細参照】"
* status ^definition = "DICOM画像のステータス"
* status ^comment = "登録済み | 利用可能 | 取消済み | エラーで入力 | 不明 http://hl7.org/fhir/ValueSet/imagingstudy-status|4.0.1"
* modality ^short = "DICOM画像で使用された撮影装置（モダリティ）【詳細参照】"
* modality ^definition = "DICOM画像で使用された撮影装置（モダリティ）"
* modality ^comment = "病理（WSI）を表すモダリティコード\"SM\"を指定する。"
* modality.code = #SM (exactly)
* subject only Reference(JP_Patient)
* subject ^short = "DICOM画像の対象患者に関する情報【詳細参照】"
* subject ^definition = "DICOM画像の対象患者に関する情報。"
* subject ^comment = "JP Core Patientリソースを参照する。"
* encounter only Reference(JP_Encounter)
* encounter ^short = "このDICOM画像を取得するきっかけとなった情報【詳細参照】"
* encounter ^definition = "このDICOM画像を取得するきっかけとなった情報。"
* encounter ^comment = "JP Core Encounterリソースを参照する。"
* started ^short = "検査開始日時、もしくは撮影装置に患者情報が届いた/入力された日時【詳細参照】"
* started ^definition = "検査開始日時、もしくは撮影装置に患者情報が届いた/入力された日時。"
* started ^comment = "病理では、検体採取日時。"
* basedOn ^short = "他のシステムから依頼されたオーダ情報【詳細参照】"
* basedOn ^definition = "他のシステムから依頼されたオーダ情報。"
* basedOn ^comment = "通常、依頼元となるServiceRequestリソースを参照する。他のシステムと連携していない場合は参照不要。"
* referrer only Reference(JP_Practitioner or JP_PractitionerRole)
* referrer ^short = "依頼医師【詳細参照】"
* referrer ^definition = "依頼医師。"
* referrer ^comment = "病理では、原則使用しない。"
* interpreter only Reference(JP_Practitioner or JP_PractitionerRole)
* interpreter ^short = "画像を診断した医師【詳細参照】"
* interpreter ^definition = "画像を診断した医師。"
* interpreter ^comment = "通常、病理医。病理では原則使用しない。"
* endpoint ^short = "DICOMのリソースが存在する位置【詳細参照】"
* endpoint ^definition = "DICOMのリソースが存在する位置。"
* endpoint ^comment = "DICOM WADO-RS、DICOM WADO-URI、DICOM QIDO-RSなどを指定する。"
* numberOfSeries ^short = "このDICOM画像検査に含まれるシリーズ数。"
* numberOfSeries ^definition = "このDICOM画像検査に含まれるシリーズ数。"
* numberOfInstances ^short = "このDICOM画像に含まれるイメージ（インスタンス）の数。"
* numberOfInstances ^definition = "このDICOM画像に含まれるイメージ（インスタンス）の数。"
* procedureReference only Reference(JP_Procedure)
* procedureReference ^short = "実施された処置に関する情報【詳細参照】"
* procedureReference ^definition = "実施された処置に関する情報。"
* procedureReference ^comment = "病理では省略してよい。使用する場合には、JP Core Procedureを参照する。"
* procedureCode ^short = "実施された処置を表すコード【詳細参照】"
* procedureCode ^definition = "実施された処置を表すコード。"
* procedureCode ^comment = "病理では原則使用しない。"
* location only Reference(JP_Location)
* location ^short = "ImagingStudyが実行された場所（画像がスキャンされた場所）を示すLocationリソースがある場合には、これを参照。"
* location ^definition = "ImagingStudyが実行された場所（画像がスキャンされた場所）を示すLocationリソースがある場合には、これを参照。"
* reasonCode ^short = "DICOM画像が依頼された理由を表す1つ以上のコード【詳細参照】"
* reasonCode ^definition = "DICOM画像が依頼された理由を表す1つ以上のコード。"
* reasonCode ^comment = "病理では原則使用しない。"
* reasonReference only Reference(JP_DiagnosticReport_Pathology)
* reasonReference ^short = "DICOM画像の実施理由に関する情報【詳細参照】"
* reasonReference ^definition = "DICOM画像の実施理由に関する情報。"
* reasonReference ^comment = "JP Core DiagnosticReportリソースを参照する。"
* note ^short = "原則、未使用"
* note ^definition = "原則、未使用"
* description ^short = "DICOM画像に関する記述。"
* description ^definition = "DICOM画像に関する記述。"
* series ^short = "DICOM画像に含まれるシリーズ（大まかな画像のグループ）。"
* series ^definition = "DICOM画像に含まれるシリーズ（大まかな画像のグループ）。"
* series.uid ^short = "シリーズを識別する一意に識別するためのUID【詳細参照】"
* series.uid ^definition = "シリーズを識別する一意に識別するためのUID。"
* series.uid ^comment = "Series Instance UID (0020,000E) の値を指定する。"
* series.number ^short = "Series Instance UIDとは別に、ユーザー（または装置）が自由に決められるシリーズ番号。"
* series.number ^definition = "Series Instance UIDとは別に、ユーザー（または装置）が自由に決められるシリーズ番号。"
* series.modality ^short = "このシリーズが取得された撮影装置（モダリティ）【詳細参照】"
* series.modality ^definition = "このシリーズが取得された撮影装置（モダリティ）。"
* series.modality ^comment = "病理（WSI）を表すモダリティコード\"SM\"を指定する。1シリーズ1モダリティで、1つのシリーズの中に複数のモダリティが混在することはない。"
* series.modality.code = #SM (exactly)
* series.description ^short = "このシリーズに関する記述。"
* series.description ^definition = "このシリーズに関する記述。"
* series.numberOfInstances ^short = "このシリーズに含まれる画像枚数。"
* series.numberOfInstances ^definition = "このシリーズに含まれる画像枚数。"
* series.endpoint ^short = "このシリーズのリソースが存在する位置。"
* series.endpoint ^definition = "このシリーズのリソースが存在する位置。"
* series.bodySite ^short = "このシリーズの対象となる解剖学的部位【詳細参照】"
* series.bodySite ^definition = "このシリーズの対象となる解剖学的部位。"
* series.bodySite ^comment = "病理では原則使用しない。"
* series.laterality ^short = "解剖学的部位の左右【詳細参照】"
* series.laterality ^definition = "解剖学的部位の左右。"
* series.laterality ^comment = "病理では原則使用しない。"
* series.specimen only Reference(JP_Specimen_Pathology)
* series.specimen ^short = "このシリーズの検体に関する情報【詳細参照】"
* series.specimen ^definition = "このシリーズの検体に関する情報。"
* series.specimen ^comment = "JP Core Specimenリソースを参照する。"
* series.started ^short = "このシリーズの開始日時【詳細参照】"
* series.started ^definition = "このシリーズの開始日時。"
* series.started ^comment = "Series Date (0008,0021)、およびSeries Time (0008,0031)（いずれもType3）に値が入っていれば、その値を指定する。"
* series.performer ^short = "このシリーズの実施医【詳細参照】"
* series.performer ^definition = "このシリーズの実施医。"
* series.performer ^comment = "病理では原則使用しない。"
* series.performer.function ^short = "このシリーズの実施医の役割【詳細参照】"
* series.performer.function ^definition = "このシリーズの実施医の役割。"
* series.performer.function ^comment = "病理では原則使用しない。"
* series.performer.actor only Reference(JP_Practitioner or JP_PractitionerRole or JP_Organization or CareTeam or JP_Patient or Device or RelatedPerson)
* series.performer.actor ^short = "このシリーズの撮影者、もしくは組織【詳細参照】"
* series.performer.actor ^definition = "このシリーズの撮影者、もしくは組織。"
* series.performer.actor ^comment = "病理では原則使用しない。"
* series.instance ^short = "シリーズに含まれるインスタンス（画像）単位の情報。"
* series.instance ^definition = "シリーズに含まれるインスタンス（画像）単位の情報。"
* series.instance.uid ^short = "インスタンス（画像）のユニークID【詳細参照】"
* series.instance.uid ^definition = "インスタンス（画像）のユニークID。"
* series.instance.uid ^comment = "SOP Instance UID (0008,0018) に値が入っていれば、その値を指定する。"
* series.instance.sopClass ^short = "SOPクラスUID【詳細参照】"
* series.instance.sopClass ^definition = "SOPクラスUID。"
* series.instance.sopClass ^comment = "病理では、主に以下の値が指定される。VL Whole Slide Microscopy Image Storage (VL全スライド顕微鏡画像保存): 1.2.840.10008.5.1.4.1.1.77.1.6"
* series.instance.number ^short = "SOP Instance UIDとは別に、ユーザー（または装置）が自由に決められるインスタンス（画像）ごとの番号【詳細参照】"
* series.instance.number ^definition = "SOP Instance UIDとは別に、ユーザー（または装置）が自由に決められるインスタンス（画像）ごとの番号。"
* series.instance.number ^comment = "Instance Number (0020,0013) に値が入っていた場合は、その値を指定する。"
* series.instance.title ^short = "画像に関する説明【詳細参照】"
* series.instance.title ^definition = "画像に関する説明。"
* series.instance.title ^comment = "部門システム側で説明を付ける場合は、その説明を指定してもよい。"
