Profile: JP_Media_Pathology
Parent: Media
Id: jp-media-pathology
Title: "JP Core Media Pathology Profile"
Description: "このプロファイルはMediaリソースに対して、病理で取得または使用される画像に関わるデータを送受信するための制約と拡張を定めたものである。"
* ^url = "http://jpfhir.jp/fhir/core/StructureDefinition/JP_Media_Pathology"
* ^status = #active
* ^version = "1.0.0"
* . ^short = "病理で取得または使用される画像に関わる情報。"
* . ^definition = "病理で取得または使用される画像に関わる情報。"
* identifier ^short = "システムが管理する、施設内で画像（JPEG等）、のメディアを一意に識別するためのID"
* identifier ^definition = "システムが管理する、施設内で画像（JPEG等）、のメディアを一意に識別するためのID"
* basedOn only Reference(JP_ServiceRequest_Common or CarePlan)
* basedOn ^short = "他のシステムから依頼されたオーダ情報。【詳細参照】"
* basedOn ^definition = "他のシステムから依頼されたオーダ情報。"
* basedOn ^comment = "通常、依頼元となるServiceRequestリソースを参照する。他のシステムと連携していない場合は参照不要。"
* partOf ^short = "参照されるイベントの一部。【詳細参照】"
* partOf ^definition = "参照されるイベントの一部。"
* partOf ^comment = "使用する場合は、基底にある Definition、Requirement、Comments の内容を参考に使用する。"
* status ^short = "メディアのステータス。【詳細参照】"
* status ^definition = "メディアのステータス。"
* status ^comment = "\"completed\" を指定する。"
* type ^short = "メディアの種類。【詳細参照】"
* type ^definition = "メディアの種類。"
* type ^comment = "使用する場合は、\"image\"を使用する。"
* modality ^short = "メディアを取得・撮影した装置（モダリティ）。【詳細参照】"
* modality ^definition = "メディアを取得・撮影した装置（モダリティ）。"
* modality ^comment = "使用する場合、臓器画像は\"XC\"、顕微鏡画像は\"GM\"を指定する。"
* view ^short = "メディアのイメージングビュー。【詳細参照】"
* view ^definition = "メディアのイメージングビュー。"
* view ^comment = "病理では原則使用しない。将来的にニーズが出てきた場合には検討する。"
* subject only Reference(JP_Patient)
* subject ^short = "メディアの対象患者に関する情報。【詳細参照】"
* subject ^definition = "メディアの対象患者に関する情報。"
* subject ^comment = "JP Core Patientリソースを参照する。"
* encounter ^short = "このメディアが生成されるきっかけとなった情報。【詳細参照】"
* encounter ^definition = "このメディアが生成されるきっかけとなった情報。"
* encounter ^comment = "病理では原則使用しない。"
* created[x] ^short = "このメディアが生成された日時。【詳細参照】"
* created[x] ^definition = "このメディアが生成された日時。"
* created[x] ^comment = "病理では原則使用しない。"
* issued ^short = "DiagnosticReportのStatusがFinalになった日時（レポート確定日時）。"
* issued ^definition = "DiagnosticReportのStatusがFinalになった日時（レポート確定日時）。"
* operator ^short = "画像を取得した人。【詳細参照】"
* operator ^definition = "画像を取得した人。"
* operator ^comment = "病理では未使用。"
* reasonCode ^short = "このメディアが生成された理由。【詳細参照】"
* reasonCode ^definition = "このメディアが生成された理由。"
* reasonCode ^comment = "病理では省略してよい。"
* bodySite ^short = "このメディアの対象となる解剖学的部位。【詳細参照】"
* bodySite ^definition = "このメディアの対象となる解剖学的部位。"
* bodySite ^comment = "病理では省略してよい。写真毎に部位が設定されている場合は指定する。"
* deviceName ^short = "このメディアを生成した装置名。【詳細参照】"
* deviceName ^definition = "このメディアを生成した装置名。"
* deviceName ^comment = "病理では原則使用しない。"
* device ^short = "メディアの収集に使用されるデバイス。【詳細参照】"
* device ^definition = "メディアの収集に使用されるデバイス。"
* device ^comment = "病理では省略してよい。"
* height ^short = "画像の高さ（ピクセル単位）（写真/ビデオ）。【詳細参照】"
* height ^definition = "画像の高さ（ピクセル単位）（写真/ビデオ）。"
* height ^comment = "使用する場合は、画像の高さ（ピクセル単位）（写真）を指定する。"
* width ^short = "画像の幅（ピクセル単位）（写真/ビデオ）。【詳細参照】"
* width ^definition = "画像の幅（ピクセル単位）（写真/ビデオ）。"
* width ^comment = "使用する場合は、画像の幅（ピクセル単位）（写真）を指定する。"
* frames ^short = "フレーム数。【詳細参照】"
* frames ^definition = "フレーム数。"
* frames ^comment = "病理では原則使用しない。"
* duration ^short = "ビデオ映像・音声向けの、秒単位の録画・記録時間。【詳細参照】"
* duration ^definition = "ビデオ映像・音声向けの、秒単位の録画・記録時間。"
* duration ^comment = "病理では原則使用しない。"
* content ^short = "埋め込まれたメディアの実際のコンテンツ、またはメディアソースファイルへの直接参照。"
* content ^definition = "埋め込まれたメディアの実際のコンテンツ、またはメディアソースファイルへの直接参照。"
* note ^short = "メディアについてのコメント。"
* note ^definition = "メディアについてのコメント。"
