Profile: JP_Specimen_Pathology
Parent: Specimen
Id: jp-specimen-pathology
Title: "JP Specimen Pathology Profile"
Description: "病理検体を表現するためのプロファイル。病理診断レポートのユースケースでは、臓器そのものを表現する。"
* ^url = "http://jpfhir.jp/fhir/core/StructureDefinition/JP_Specimen_Pathology"
* ^status = #draft
* ^version = "1.0.0"
* ^publisher = "日本医療情報学会 FHIR国内実装基盤研究会"
* . ^short = "病理検体"
* . ^definition = "病理検体"
* identifier ^short = "オーダ側（依頼元）が発番した検体識別番号"
* identifier ^definition = "オーダ側（依頼元）が発番した検体識別番号"
* accessionIdentifier ^short = "病理検査側で発番した検体識別番号"
* accessionIdentifier ^definition = "病理検査側で発番した検体識別番号"
* status ^short = "検体の利用可能性"
* status ^definition = "検体の利用可能性"
* type ^short = "検査材料"
* type ^definition = "検査材料"
* subject only Reference(JP_Patient)
* subject ^short = "検体採取した患者リソース（JP_Patient）を参照"
* subject ^definition = "検体採取した患者リソース（JP_Patient）を参照"
* receivedTime ^short = "検体の受付日時"
* receivedTime ^definition = "検体の受付日時"
* request only Reference(JP_ServiceRequest_Common)
* request ^short = "依頼目的。病理検査依頼元を示すServiceRequestリソースを参照"
* request ^definition = "依頼目的。病理検査依頼元を示すServiceRequestリソースを参照"
* collection.collector ^short = "検体採取した人"
* collection.collector ^definition = "検体採取した人"
* collection.collected[x] ^short = "検体採取日時"
* collection.collected[x] ^definition = "検体採取日時"
* collection.duration ^short = "検体採取期間"
* collection.duration ^definition = "検体採取期間"
* collection.quantity ^short = "検体量"
* collection.quantity ^definition = "検体量"
* collection.method ^short = "採取方法"
* collection.method ^definition = "採取方法"
* collection.bodySite ^short = "検体部位"
* collection.bodySite ^definition = "検体部位"
* note ^short = "検体に関する特記事項を記載"
* note ^definition = "検体に関する特記事項を記載"
