// ImplementationGuide
Alias: $FHIRJPCoreImplementationGuide = http://jpfhir.jp/fhir/core/ImplementationGuide/jpfhir.jp.core

// StructureDefinition: Profile, DataType
Alias: $JP_AllergyIntolerance = http://jpfhir.jp/fhir/core/StructureDefinition/JP_AllergyIntolerance
Alias: $JP_Binary = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Binary
Alias: $JP_CarePlan = http://jpfhir.jp/fhir/core/StructureDefinition/JP_CarePlan
Alias: $JP_Condition = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Condition
Alias: $JP_Condition_Diagnosis = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Condition_Diagnosis
Alias: $JP_Consent = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Consent
Alias: $JP_Coverage = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Coverage
Alias: $JP_Device = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Device
Alias: $JP_DiagnosticReport_Common = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_Common
Alias: $JP_DiagnosticReport_DentalOral = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_DentalOral
Alias: $JP_DiagnosticReport_Endoscopy = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_Endoscopy
Alias: $JP_DiagnosticReport_LabResult = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_LabResult
Alias: $JP_DiagnosticReport_Microbiology = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_Microbiology
Alias: $JP_DiagnosticReport_Radiology = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DiagnosticReport_Radiology
Alias: $JP_DocumentReference = http://jpfhir.jp/fhir/core/StructureDefinition/JP_DocumentReference
Alias: $JP_Encounter = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Encounter
Alias: $JP_FamilyMemberHistory = http://jpfhir.jp/fhir/core/StructureDefinition/JP_FamilyMemberHistory
Alias: $JP_HumanName = http://jpfhir.jp/fhir/core/StructureDefinition/JP_HumanName
Alias: $JP_ImagingStudy_Endoscopy = http://jpfhir.jp/fhir/core/StructureDefinition/JP_ImagingStudy_Endoscopy
Alias: $JP_ImagingStudy_Radiology = http://jpfhir.jp/fhir/core/StructureDefinition/JP_ImagingStudy_Radiology
Alias: $JP_Immunization = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Immunization
Alias: $JP_Location = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Location
Alias: $JP_Media_Endoscopy = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Media_Endoscopy
Alias: $JP_Medication = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Medication
Alias: $JP_MedicationAdministration = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationAdministration
Alias: $JP_MedicationAdministration_Injection = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationAdministration_Injection
Alias: $JP_MedicationAdministrationBase = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationAdministrationBase
Alias: $JP_MedicationDispense = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDispense
Alias: $JP_MedicationDispense_Injection = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDispense_Injection
Alias: $JP_MedicationDispenseBase = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDispenseBase
Alias: $JP_MedicationDosage = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDosage
Alias: $JP_MedicationDosage_Injection = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDosage_Injection
Alias: $JP_MedicationDosageBase = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDosageBase
Alias: $JP_MedicationQuantity = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationQuantity
Alias: $JP_MedicationRange = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRange
Alias: $JP_MedicationRange_UnitOfTime = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRange_UnitOfTime
Alias: $JP_MedicationRatio_Amount = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRatio_Amount
Alias: $JP_MedicationRatio_DosePerDay = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRatio_DosePerDay
Alias: $JP_MedicationRatio_DosePerPeriod = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRatio_DosePerPeriod
Alias: $JP_MedicationRequest = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRequest
Alias: $JP_MedicationRequest_Injection = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationRequest_Injection
Alias: $JP_MedicationSimpleQuantity = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationSimpleQuantity
Alias: $JP_MedicationStatement = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationStatement
Alias: $JP_MedicationStatement_Injection = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationStatement_Injection
Alias: $JP_MedicationTiming = http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationTiming
Alias: $JP_Observation_BodyMeasurement = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_BodyMeasurement
Alias: $JP_Observation_Common = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Common
Alias: $JP_Observation_DentalOral_eCS = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_DentalOral_eCS
Alias: $JP_Observation_DentalOral_MissingToothCondition = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_DentalOral_MissingToothCondition
Alias: $JP_Observation_DentalOral_ToothExistence = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_DentalOral_ToothExistence
Alias: $JP_Observation_DentalOral_ToothTreatmentCondition = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_DentalOral_ToothTreatmentCondition
Alias: $JP_OBservation_Electrocardiogram = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Electrocardiogram
Alias: $JP_Observation_Endoscopy = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Endoscopy
Alias: $JP_Observation_LabResult = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_LabResult
Alias: $JP_Observation_Microbiology = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Microbiology
Alias: $JP_Observation_PhysicalExam = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_PhysicalExam
Alias: $JP_Observation_Radiology_Findings = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Radiology_Findings
Alias: $JP_Observation_Radiology_Impression = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_Radiology_Impression
Alias: $JP_Observation_SocialHistory = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_SocialHistory
Alias: $JP_Observation_VitalSigns = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Observation_VitalSigns
Alias: $JP_Organization = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Organization
Alias: $JP_Patient = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Patient
Alias: $JP_Practitioner = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Practitioner
Alias: $JP_PractitionerRole = http://jpfhir.jp/fhir/core/StructureDefinition/JP_PractitionerRole
Alias: $JP_Procedure = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Procedure
Alias: $JP_RelatedPerson = http://jpfhir.jp/fhir/core/StructureDefinition/JP_RelatedPerson
Alias: $JP_ServiceRequest_Common = http://jpfhir.jp/fhir/core/StructureDefinition/JP_ServiceRequest_Common
Alias: $JP_Specimen_Common = http://jpfhir.jp/fhir/core/StructureDefinition/JP_Specimen_Common

// StructureDefinition: Extension
Alias: $JP_Condition_DiseaseOutcome = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Condition_DiseaseOutcome
Alias: $JP_Condition_DiseasePostfixModifier = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Condition_DiseasePostfixModifier
Alias: $JP_Condition_DiseasePrefixModifier = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Condition_DiseasePrefixModifier
Alias: $JP_Coverage_InsuredPersonNumber = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber
Alias: $JP_Coverage_InsuredPersonSubNumber = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonSubNumber
Alias: $JP_Coverage_InsuredPersonSymbol = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonSymbol
Alias: $JP_Immunization_CertificatedDate = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Immunization_CertificatedDate
Alias: $JP_Immunization_DueDateOfNextDose = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Immunization_DueDateOfNextDose
Alias: $JP_Immunization_ManufacturedDate = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Immunization_ManufacturedDate
Alias: $JP_Medication_Ingredient_DrugNo = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Medication_Ingredient_DrugNo
Alias: $JP_Medication_IngredientStrength_StrengthType = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Medication_IngredientStrength_StrengthType
Alias: $JP_MedicationAdministration_Location = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationAdministration_Location
Alias: $JP_MedicationAdministration_RequestAuthoredOn = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationAdministration_RequestAuthoredOn
Alias: $JP_MedicationAdministration_RequestDepartment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationAdministration_RequestDepartment
Alias: $JP_MedicationAdministration_Requester = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationAdministration_Requester
Alias: $JP_MedicationAdministration_UncategorizedComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationAdministration_UncategorizedComment
Alias: $JP_MedicationDispense_Preparation = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDispense_Preparation
Alias: $JP_MedicationDosage_Device = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_Device
Alias: $JP_MedicationDosage_DosageComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_DosageComment
Alias: $JP_MedicationDosage_Line = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_Line
Alias: $JP_MedicationDosage_LineComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_LineComment
Alias: $JP_MedicationDosage_MethodComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_MethodComment
Alias: $JP_MedicationDosage_PeriodOfUse = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_PeriodOfUse
Alias: $JP_MedicationDosage_RateComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_RateComment
Alias: $JP_MedicationDosage_RouteComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_RouteComment
Alias: $JP_MedicationDosage_SiteComment = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_SiteComment
Alias: $JP_MedicationDosage_UsageDuration = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationDosage_UsageDuration
Alias: $JP_MedicationRequest_DispenseRequest_ExpectedRepeatCount = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DispenseRequest_ExpectedRepeatCount
Alias: $JP_MedicationRequest_DispenseRequest_InstructionForDispense = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DispenseRequest_InstructionForDispense
Alias: $JP_Observation_DentalOral_BodySiteStatus = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_DentalOral_BodySiteStatus
Alias: $JP_Observation_DentalOral_BodyStructure = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_DentalOral_BodyStructure
Alias: $JP_Observation_Electrocardiogram_DeviceInterpretation = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_Electrocardiogram_DeviceInterpretation
Alias: $JP_Observation_Electrocardiogram_Duration = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_Electrocardiogram_Duration
Alias: $JP_Observation_Electrocardiogram_NumberOfLead = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_Electrocardiogram_NumberOfLead
Alias: $JP_Observation_Electrocardiogram_StressType = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Observation_Electrocardiogram_StressType
Alias: $JP_Organization_InsuranceOrganizationCategory = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationCategory
Alias: $JP_Organization_InsuranceOrganizationNo = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationNo
Alias: $JP_Organization_PrefectureNo = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_PrefectureNo
Alias: $JP_Patient_Race = http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Patient_Race

// CapabilityStatement
Alias: $JP_Client_CapabilityStatement = http://jpfhir.jp/fhir/core/CapabilityStatement/JP_Client_CapabilityStatement
Alias: $JP_Server_CapabilityStatement = http://jpfhir.jp/fhir/core/CapabilityStatement/JP_Server_CapabilityStatement

// SearchParameter
Alias: $JP_Coverage_InsuredPersonNumber_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Coverage_InsuredPersonNumber_SP
Alias: $JP_Coverage_InsuredPersonSubNumber_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Coverage_InsuredPersonSubNumber_SP
Alias: $JP_Coverage_InsuredPersonSymbol_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Coverage_InsuredPersonSymbol_SP
Alias: $JP_MedicationRequest_Start_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_MedicationRequest_Start_SP
Alias: $JP_Organization_InsuranceOrganizationCategory_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_InsuranceOrganizationCategory_SP
Alias: $JP_Organization_InsuranceOrganizationNo_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_InsuranceOrganizationNo_SP
Alias: $JP_Organization_PrefectureNo_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_PrefectureNo_SP
Alias: $JP_Patient_KanaSort_SP = http://jpfhir.jp/fhir/core/SearchParameter/JP_Patient_KanaSort_SP

// CodeSystem
Alias: $JP_BodySite_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_BodySite_CS
Alias: $JP_ConclusionCodeJed_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ConclusionCodeJed_CS
Alias: $JP_ConditionDiseaseCodeICD10_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/ICD10-2013-full
Alias: $JP_ConditionDiseaseOutcomeHL70241_CS = http://jpfhir.jp/fhir/core/CodeSystem/HL70241
Alias: $JP_ConditionDiseaseOutcomeJHSD0006_CS = http://jpfhir.jp/fhir/core/CodeSystem/JHSD0006
Alias: $JP_ConditionDiseaseOutcomeReceipt_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ConditionDiseaseOutcomeReceipt_CS
Alias: $JP_ConditionSeverity_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ConditionSeverity_CS
Alias: $JP_DentalBodySite_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalBodySite_CS
Alias: $JP_DentalBodySiteStatus_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalBodySiteStatus_CS
Alias: $JP_DentalBodyStructure_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalBodyStructure_CS
Alias: $JP_DentalFundamentalStatus_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalFundamentalStatus_CS
Alias: $JP_DentalMissingTeethObservation_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalMissingTeethObservation_CS
Alias: $JP_DentalPresentTeethObservation_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalPresentTeethObservation_CS
Alias: $JP_DentalSimpleMissingTeethObservation_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalSimpleMissingTeethObservation_CS
Alias: $JP_DentalSimplePresentTeethObservation_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DentalSimplePresentTeethObservation_CS
Alias: $JP_Department_SsMix_CS = http://jami.jp/SS-MIX2/CodeSystem/ClinicalDepartment //urn:oid:1.2.392.200250.2.2.2
Alias: $JP_DICOMSopClass_CS = http://hl7.org/fhir/uv/imaging-service-request-ig/CodeSystem/dicom-uids
Alias: $JP_Disease_Claim_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/masterB-disease    // 支払基金	傷病名コード   
Alias: $JP_Disease_MEDIS_Concept_CS = http://medis.or.jp/CodeSystem/master-disease-exCode // MEDIS病名交換用コード   //urn:oid:1.2.392.200119.4.101.6
Alias: $JP_Disease_MEDIS_ManagementID_CS = http://medis.or.jp/CodeSystem/master-disease-keyNumber    // MEDIS病名管理番号
Alias: $JP_DiseaseCategory_WHO_ICD10_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/ICD10-2013-full  // ICD10  HL7 regisered
Alias: $JP_DocumentCodes_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_DocumentCodes_CS
Alias: $JP_EndoscopyTerminologyCodesJED_CS = urn:oid:1.2.392.200270.4.1000.1
Alias: $JP_InsuredPersonCategory_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/InsuredPersonCategory
Alias: $JP_JfagyFoodAllergen_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyFoodAllergen_CS
Alias: $JP_JfagyMedicationAllergen_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyMedicationAllergen_CS
Alias: $JP_JfagyNonFoodNonMedicationAllergen_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_JfagyNonFoodNonMedicationAllergen_CS
Alias: $JP_MedicalFeeScoreType_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/MedicationFeeScoreType //urn:oid:1.2.392.100495.20.3.22
Alias: $JP_MedicalLicenseCertificate_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicalLicenseCertificate_CS
Alias: $JP_MedicationAsNeededConditionJAMI_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicationAsNeededConditionJAMI_CS
Alias: $JP_MedicationAsNeededConditionMERIT9_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicationAsNeededConditionMERIT9_CS
Alias: $JP_MedicationBodySiteJAMIExternal_CS = http://jami.jp/CodeSystem/MedicationBodySiteExternal //urn:oid:1.2.392.200250.2.2.20.32
Alias: $JP_MedicationCategoryJHSI0001_CS = http://jpfhir.jp/fhir/core/CodeSystem/JHSI0001
Alias: $JP_MedicationCategoryJHSP0007_CS = http://jpfhir.jp/fhir/core/CodeSystem/JHSP0007
Alias: $JP_MedicationCategoryMERIT9_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicationCategoryMERIT9_CS
Alias: $JP_MedicationCodeCommon_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/MedicationGeneralOrderCode // urn:oid:1.2.392.100495.20.1.81 =>urn:oid:1.2.392.100495.20.2.81
Alias: $JP_MedicationCodeHOT13_CS = http://medis.or.jp/CodeSystem/master-HOT13 //urn:oid:1.2.392.200119.4.402.1
Alias: $JP_MedicationCodeHOT7_CS = http://medis.or.jp/CodeSystem/master-HOT7 //urn:oid:1.2.392.200119.4.403.2
Alias: $JP_MedicationCodeHOT9_CS = http://medis.or.jp/CodeSystem/master-HOT9 //urn:oid:1.2.392.200119.4.403.1
Alias: $JP_MedicationCodeYJ_CS = http://capstandard.jp/iyaku.info/CodeSystem/YJ-code //urn:oid:1.2.392.100495.20.1.73
Alias: $JP_MedicationExampleDosageComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageComment_CS
Alias: $JP_MedicationExampleLine_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationRequestDosageInstructionLine_CS
Alias: $JP_MedicationExampleLineComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageLineComment_CS
Alias: $JP_MedicationExampleMethodComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageMethodComment_CS
Alias: $JP_MedicationExampleRateComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageRateComment_CS
Alias: $JP_MedicationExampleRouteComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageRouteComment_CS
Alias: $JP_MedicationExampleSiteComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationDosageSiteComment_CS
Alias: $JP_MedicationExampleUncategorizedComment_CS = http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationAdministrationUncategorizedComment_CS
Alias: $JP_MedicationFormMERIT9_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MedicationFormMERIT9_CS
Alias: $JP_MedicationIngredientStrengthStrengthType_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/MedicationIngredientStrengthStrengthType //urn:oid:1.2.392.100495.20.2.22
Alias: $JP_MedicationInstructionForDispenseJHSP0002_CS = http://jpfhir.jp/fhir/core/CodeSystem/JHSP0002
Alias: $JP_MedicationMethodJAMIBasicUsage_CS = http://jami.jp/CodeSystem/MedicationMethodBasicUsage //urn:oid:1.2.392.200250.2.2.20.30
Alias: $JP_MedicationMethodJAMIDetailUsage_CS = http://jami.jp/CodeSystem/MedicationMethodDetailUsage //urn:oid:1.2.392.200250.2.2.20.40
Alias: $JP_MedicationMethodJHSI0003_CS = http://jpfhir.jp/fhir/core/CodeSystem/JHSI0003
Alias: $JP_MedicationRouteHL70162_CS = http://jpfhir.jp/fhir/core/CodeSystem/route-codes
Alias: $JP_MedicationSubstitutionNotAllowedReason_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/MedicationSubstitutionProhibittedCategory //urn:oid:1.2.392.100495.20.2.41
Alias: $JP_MedicationUnitMERIT9_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/MedicationUnitMERIT9Code //urn:oid:1.2.392.100495.20.2.101
Alias: $JP_MedicationUsageJAMI_CS = http://jami.jp/CodeSystem/MedicationUsage //urn:oid:1.2.392.200250.2.2.20.20
Alias: $JP_MedicationUsageJAMIAdditional_CS = http://jami.jp/CodeSystem/MedicationUsageAdditional //urn:oid:1.2.392.200250.2.2.20.22
Alias: $JP_Microbiology_AntiMicrobialDrug_CS = urn:oid:1.2.392.100495.10.3.100.5.11.5.2
Alias: $JP_Microbiology_InfectiousAgent_CS = urn:oid:1.2.392.100495.10.3.100.5.27.6.1
Alias: $JP_MicrobiologyCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_MicrobiologyCategory_CS
Alias: $JP_Modifier_Disease_Claim_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/masterZ-disease-modifier //  支払基金	修飾語コード    
Alias: $JP_Modifier_MEDIS_Concept_CS = http://medis.or.jp/CodeSystem/master-disease-modExCode   //MEDIS病名交換用修飾コード //urn:oid:1.2.392.200119.4.201.5
Alias: $JP_Modifier_MEDIS_ManagementID_CS = http://medis.or.jp/CodeSystem/master-disease-modKeyNumber   //MEDIS病名管理修飾コード    //urn:oid:1.2.392.200119.4.201.2
Alias: $JP_ObservationBodyMeasurementCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationBodyMeasurementCategory_CS
Alias: $JP_ObservationBodyMeasurementCode_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationBodyMeasurementCode_CS
Alias: $JP_ObservationDentalCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationDentalCategory_CS
Alias: $JP_ObservationElectrocardiogramDuration_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationElectrocardiogramDuration_CS
Alias: $JP_ObservationElectrocardiogramExtraCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationElectrocardiogramExtraCategory_CS
Alias: $JP_ObservationElectrocardiogramInterpretationCode_CS =  http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationElectrocardiogramInterpretationCode_CS
Alias: $JP_ObservationElectrocardiogramStressType_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationElectrocardiogramStressType_CS
Alias: $JP_ObservationLabResultCode_CS = http://medis.or.jp/CodeSystem/master-JLAC10-17digits //urn:oid:1.2.392.200119.4.504
Alias: $JP_ObservationMethod_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationMethod_CS
Alias: $JP_ObservationPhysicalExamBodySite_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationPhysicalExamBodySite_CS
Alias: $JP_ObservationPhysicalExamMethod_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationPhysicalExamMethod_CS
Alias: $JP_ObservationSocialHistoryCode_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationSocialHistoryCode_CS
Alias: $JP_ObservationVitalSignsCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ObservationVitalSignsCategory_CS
Alias: $JP_ObservationVitalSignsCode_CS = http://medis.or.jp/CodeSystem/master-nursingObservationKeyCode //urn:oid:1.2.392.200119.4.804
Alias: $JP_PhysicalExamCode_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_PhysicalExamCode_CS
Alias: $JP_PractitionerRole_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_PractitionerRole_CS
Alias: $JP_PrefectureNumber_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/PrefectureNo-2digits //urn:oid:1.2.392.100495.20.3.21
Alias: $JP_ProcedureCategory_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/masterS-medicalProcedure
Alias: $JP_ProcedureCodesDental_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/masterH-dentalProcedure
Alias: $JP_ProcedureCodesICHI_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureCodesMedical_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ProcedureCodesMedical_CS
Alias: $JP_ProcedureCodesNurse_CS =  http://medis.or.jp/CodeSystem/master-nursingAction-16digits // urn:oid:1.2.392.200119.4.701->704 看護行為テーブル
Alias: $JP_ProcedureCodesSTEM7_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ProcedureCodesSTEM7_CS
Alias: $JP_ProcedureCondition_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureDeviceAction_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureDeviceKind_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureFollowUp_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureNotPerformedReason_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ProcedureNotPerformedReason_CS
Alias: $JP_ProcedureOutcome_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_ProcedureOutcome_CS
Alias: $JP_ProcedureReason_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS
Alias: $JP_SimpleObservationCategory_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_SimpleObservationCategory_CS
Alias: $JP_Undefined_CS = http://jpfhir.jp/fhir/core/CodeSystem/JP_Undefined_CS

// Clinsでは定義されているが、JP Coreでは未定義
// Alias: $JP_BodySite_MEDIS_Concept_CS = http://medis.or.jp/CodeSystem/master-disease-modExCode   //MEDIS病名交換用修飾コード //urn:oid:1.2.392.200119.4.201.5
// Alias: $JP_BodySite_MEDIS_ManagementID_CS = http://medis.or.jp/CodeSystem/master-disease-modKeyNumber   //MEDIS病名管理修飾コード    //urn:oid:1.2.392.200119.4.201.2
// Alias: $JP_BodySite_Disease_Claim_CS = http://jpfhir.jp/fhir/core/mhlw/CodeSystem/masterZ-disease-modifier //  支払基金	修飾語コード 


// ValueSet
Alias: $JP_AllergyIntolerance_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_AllergyIntolerance_VS
Alias: $JP_ConclusionCodesJed_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConclusionCodesJed_VS
Alias: $JP_Condition_BodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Condition_BodySite_VS
Alias: $JP_ConditionDiseaseCodeICD10_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/ICD10-2013-full
Alias: $JP_ConditionDiseaseCodeReceipt_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionDiseaseCodeReceipt_VS
Alias: $JP_ConditionDiseaseOutcomeHL70241_JHSD0006_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionDiseaseOutcomeHL70241_JHSD0006_VS
Alias: $JP_ConditionDiseaseOutcomeHL70241_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionDiseaseOutcomeHL70241_VS
Alias: $JP_ConditionDiseaseOutcomeJHSD0006_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionDiseaseOutcomeJHSD0006_VS
Alias: $JP_ConditionDiseaseOutcomeReceipt_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionDiseaseOutcomeReceipt_VS
Alias: $JP_ConditionSeverity_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ConditionSeverity_VS
Alias: $JP_DentalBodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalBodySite_VS
Alias: $JP_DentalBodySiteStatus_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalBodySiteStatus_VS
Alias: $JP_DentalBodyStructure_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalBodyStructure_VS
Alias: $JP_DentalFundamentalStatus_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalFundamentalStatus_VS
Alias: $JP_DentalMissingTeethObservation_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalMissingTeethObservation_VS
Alias: $JP_DentalPresentTeethObservation_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalPresentTeethObservation_VS
Alias: $JP_DentalSimpleMissingTeethObservation_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalSimpleMissingTeethObservation_VS
Alias: $JP_DentalSimplePresentTeethObservation_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DentalSimplePresentTeethObservation_VS
Alias: $JP_Department_SsMix_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Department_SsMix_VS
Alias: $JP_Department_SsMix2Digits_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Department_SsMix2Digits_VS
Alias: $JP_Department_SsMix3Digits_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Department_SsMix3Digits_VS
Alias: $JP_DiagnosticReportCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DiagnosticReportCategory_VS
Alias: $JP_DICOMModality_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DICOMModality_VS
Alias: $JP_DICOMSopClass_VS = http://hl7.org/fhir/uv/imaging-service-request-ig/ValueSet/dicom-sop-classes
Alias: $JP_DICONRadLexPlaybook_VS = http://playbook.radlex.org/playbook/SearchRadlexAction
Alias: $JP_Disease_Claim_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/masterB-disease    // 支払基金	傷病名コード
Alias: $JP_Disease_MEDIS_Concept_VS = http://medis.or.jp/ValueSet/master-disease-exCode // MEDIS病名交換用コード
Alias: $JP_Disease_MEDIS_ManagementID_VS = http://medis.or.jp/ValueSet/master-disease-keyNumber    // MEDIS病名管理番号
Alias: $JP_DiseaseICD10_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/ICD10-2013-full_VS
Alias: $JP_DocumentCodes_DiagnosticReport_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DocumentCodes_DiagnosticReport_VS
Alias: $JP_DocumentCodes_Endoscopy_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DocumentCodes_Endoscopy_VS
Alias: $JP_DocumentCodes_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_DocumentCodes_VS
Alias: $JP_ImagingStudy_Endoscopy_BodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ImagingStudy_Endoscopy_BodySite_VS
Alias: $JP_ImagingStudy_Radiology_BodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ImagingStudy_Radiology_BodySite_VS
Alias: $JP_MedicalFeeScoreType_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicalFeeScoreType_VS
Alias: $JP_MedicalLicenseCertificate_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicalLicenseCertificate_VS
Alias: $JP_MedicationAsNeededConditionJAMI_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationAsNeededConditionJAMI_VS
Alias: $JP_MedicationAsNeededConditionMERIT9_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationAsNeededConditionMERIT9_VS
Alias: $JP_MedicationBodySiteJAMIExternal_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationBodySiteJAMIExternal_VS
Alias: $JP_MedicationCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCategory_VS
Alias: $JP_MedicationCategoryInjection_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCategoryInjeciton_VS
Alias: $JP_MedicationCategoryJHSI0001_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCategoryJHSI0001_VS
Alias: $JP_MedicationCategoryJHSP0007_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCategoryJHSP0007_VS
Alias: $JP_MedicationCategoryMERIT9_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCategoryMERIT9_VS
Alias: $JP_MedicationCode_Immunization_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCode_Immunization_VS
Alias: $JP_MedicationCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCode_VS
Alias: $JP_MedicationCodeCommon_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCodeCommon_VS
Alias: $JP_MedicationCodeHOT13_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCodeHOT13_VS
Alias: $JP_MedicationCodeHOT7_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCodeHOT7_VS
Alias: $JP_MedicationCodeHOT9_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCodeHOT9_VS
Alias: $JP_MedicationCodeYJ_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationCodeYJ_VS
Alias: $JP_MedicationExampleDosageComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageComment_VS
Alias: $JP_MedicationExampleLine_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_DosageInstructionLine_VS
Alias: $JP_MedicationExampleLineComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageLineComment_VS
Alias: $JP_MedicationExampleMethodComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageMethodComment_VS
Alias: $JP_MedicationExampleRateComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageRateComment_VS
Alias: $JP_MedicationExampleRouteComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageRouteComment_VS
Alias: $JP_MedicationExampleSiteComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationDosageSiteComment_VS
Alias: $JP_MedicationExampleUncategorizedComment_VS = http://jpfhir.jp/fhir/Examples/ValueSet/JP_MedicationAdministrationUncategorizedComment_VS
Alias: $JP_MedicationFormMERIT9_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationFormMERIT9_VS
Alias: $JP_MedicationIngredientStrengthStrengthType_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationIngredientStrengthStrengthType_VS
Alias: $JP_MedicationInstructionForDispenseJHSP0002_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationInstructionForDispenseJHSP0002_VS
Alias: $JP_MedicationMethodJAMIBasicUsage_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationMethodJAMIBasicUsage_VS
Alias: $JP_MedicationMethodJAMIDetailUsage_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationMethodJAMIDetailUsage_VS
Alias: $JP_MedicationMethodJHSI0003_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationMethodJHSI0003_VS
Alias: $JP_MedicationRouteHL70162_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationRouteHL70162_VS
Alias: $JP_MedicationSubstitutionNotAllowedReason_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationSubstitutionNotAllowedReason_VS
Alias: $JP_MedicationUnitMERIT9_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationUnitMERIT9_VS
Alias: $JP_MedicationUsageInjection_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationUsageInjection_VS
Alias: $JP_MedicationUsageJAMI_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationUsageJAMI_VS
Alias: $JP_MedicationUsageJAMIAdditional_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MedicationUsageJAMIAdditional_VS
Alias: $JP_Microbiology_AntiMicrobialDrug_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Microbiology_AntiMicrobialDrug_VS
Alias: $JP_Microbiology_InfectiousAgent_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Microbiology_InfectiousAgent_VS
Alias: $JP_MicrobiologyCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_MicrobiologyCategory_VS
Alias: $JP_Modifier_Disease_Claim_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/masterZ-disease-modifier //  支払基金	修飾語コード    
Alias: $JP_Modifier_MEDIS_Concept_VS = http://medis.or.jp/ValueSet/master-disease-modExCode   //MEDIS病名交換用修飾コード 
Alias: $JP_Modifier_MEDIS_ManagementID_VS = http://medis.or.jp/ValueSet/master-disease-modKeyNumber   //MEDIS病名管理修飾コード
Alias: $JP_Observation_BodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Observation_BodySite_VS
Alias: $JP_ObservationBodyMeasurementCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationBodyMeasurementCategory_VS
Alias: $JP_ObservationBodyMeasurementCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationBodyMeasurementCode_VS
Alias: $JP_ObservationDetailedDentalCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationDetailedDentalCategory_VS
Alias: $JP_ObservationElectrocardiogramComponentCode_VS =  http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationElectrocardiogramComponentCode_VS
Alias: $JP_ObservationElectrocardiogramDuration_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationElectrocardiogramDuration_VS
Alias: $JP_ObservationElectrocardiogramExtraCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationElectrocardiogramExtraCategory_VS
Alias: $JP_ObservationElectrocardiogramInterpretationCode_VS =  http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationElectrocardiogramInterpretationCode_VS
Alias: $JP_ObservationElectrocardiogramStressType_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationElectrocardiogramStressType_VS
Alias: $JP_ObservationEndoscopyCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationEndoscopyCode_VS
Alias: $JP_ObservationEndoscopyValueJed_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationEndoscopyValueJed_VS
Alias: $JP_ObservationLabResultCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationLabResultCode_VS
Alias: $JP_ObservationMethod_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationMethod_VS
Alias: $JP_ObservationPhysicalExamBodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationPhysicalExamBodySite_VS
Alias: $JP_ObservationPhysicalExamMethod_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationPhysicalExamMethod_VS
Alias: $JP_ObservationRadiologyCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationRadiologyCode_VS
Alias: $JP_ObservationSocialHistoryCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationSocialHistoryCode_VS
Alias: $JP_ObservationVitalSignsCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationVitalSignsCategory_VS
Alias: $JP_ObservationVitalSignsCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ObservationVitalSignsCode_VS
Alias: $JP_PhysicalExamCode_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_PhysicalExamCode_VS
Alias: $JP_PractitionerRole_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_PractitionerRole_VS
Alias: $JP_PrefectureNumber_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_PrefectureNumber_VS
Alias: $JP_ProcedureBodySite_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureBodySite_VS
Alias: $JP_ProcedureCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCategory_VS
Alias: $JP_ProcedureCodesDental_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCodesDental_VS
Alias: $JP_ProcedureCodesICHI_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCodesICHI_VS
Alias: $JP_ProcedureCodesMedical_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCodesMedical_VS
Alias: $JP_ProcedureCodesNurse_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCodesNurse_VS
Alias: $JP_ProcedureCodesSTEM7_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCodesSTEM7_VS
Alias: $JP_ProcedureCondition_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureCondition_VS
Alias: $JP_ProcedureDeviceAction_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureDeviceAction_VS
Alias: $JP_ProcedureDeviceKind_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureDeviceKind_VS
Alias: $JP_ProcedureFollowUp_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureFollowUp_VS
Alias: $JP_ProcedureNotPerformedReason_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureNotPerformedReason_VS
Alias: $JP_ProcedureOutcome_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureOutcome_VS
Alias: $JP_ProcedurePerformerRole_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedurePerformerRole_VS
Alias: $JP_ProcedureReason_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ProcedureReason_VS
Alias: $JP_ReasonCodesJed_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_ReasonCodesJed_VS
Alias: $JP_SimpleObservationCategory_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_SimpleObservationCategory_VS
Alias: $JP_Undefined_VS = http://jpfhir.jp/fhir/core/ValueSet/JP_Undefined_VS

// Alias: $JP_BodySite_MEDIS_Concept_VS = http://medis.or.jp/ValueSet/master-disease-modExCode

// Alias: $JP_BodySite_MEDIS_ManagementID_VS = http://medis.or.jp/ValueSet/master-disease-modKeyNumber
// Alias: $JP_BodySite_Disease_Claim_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/masterZ-disease-modifier //  支払基金	修飾語コード
// Alias: $JP_Modifier_Disease_Claim_VS = http://jpfhir.jp/fhir/core/mhlw/ValueSet/masterZ-disease-modifier //  支払基金	修飾語コード

//system値
Alias: $JP_IdSystem_InsurerNumber = http://jpfhir.jp/fhir/core/mhlw/IdSystem/InsurerNumber  //urn:oid:1.2.392.100495.20.3.61
Alias: $JP_IdSystem_MedicalOrganizationID = http://jpfhir.jp/fhir/core/mhlw/IdSystem/MedicalOrganizationID //urn:oid:1.2.392.100495.20.3.23
Alias: $JP_IdSystem_PrescriptionDocumentID = urn:oid:1.2.392.100495.20.3.11
Alias: $JP_IdSystemMedicalRegistrationNumber = http://jpfhir.jp/fhir/core/mhlw/IdSystem/medicalRegistrationNumber   //urn:oid:1.2.392.100495.20.3.31
Alias: $JP_Medication_RPGroupNumber = http://jpfhir.jp/fhir/core/mhlw/IdSystem/Medication-RPGroupNumber //urn:oid:1.2.392.100495.20.3.81
Alias: $JP_MedicationAdministrationIndex = http://jpfhir.jp/fhir/core/mhlw/IdSystem/MedicationAdministrationIndex  //	urn:oid:1.2.392.100495.20.3.82
Alias: $JP_ResourceInstance_Identifier = http://jpfhir.jp/fhir/core/IdSystem/resourceInstance-identifier
