### Profiles
* [JP Core Medication （薬剤）プロファイル][JP_Medication]
* [JP Core MedicationRequest （内服・外用薬剤処方）プロファイル][JP_MedicationRequest]
* [JP Core MedicationRequest Injection （注射薬剤処方）プロファイル][JP_MedicationRequest_Injection]
* [JP Core MedicationDispense （内服・外用薬剤処方調剤・払い出し記録）プロファイル][JP_MedicationDispense]
* [JP Core MedicationDispense Injection （注射薬剤処方調剤・払い出し記録）プロファイル][JP_MedicationDispense_Injection]
* [JP Core MedicationAdministration （内服・外用薬剤投与実施情報）プロファイル][JP_MedicationAdministration]
* [JP Core MedicationAdministration Injection （注射薬剤投与実施情報）プロファイル][JP_MedicationAdministration_Injection]
* [JP Core Immunization （予防接種記録）プロファイル][JP_Immunization]

### Extensions
* [JP_Immunization_CertificatedDate]
* [JP_Immunization_DueDateOfNextDose]
* [JP_Immunization_ManufacturedDate]
* [JP_Medication_Ingredient_DrugNo]
* [JP_Medication_IngredientStrength_StrengthType]
* [JP_MedicationAdministration_Location]
* [JP_MedicationAdministration_RequestAuthoredOn]
* [JP_MedicationAdministration_RequestDepartment]
* [JP_MedicationAdministration_Requester]
* [JP_MedicationAdministration_UncategorizedComment]
* [JP_MedicationDispense_Preparation]
* [JP_MedicationRequest_DispenseRequest_ExpectedRepeatCount]
* [JP_MedicationRequest_DispenseRequest_InstructionForDispense]
* [JP_MedicationDosage_Device]
* [JP_MedicationDosage_DosageComment]
* [JP_MedicationDosage_Line]
* [JP_MedicationDosage_LineComment]
* [JP_MedicationDosage_MethodComment]
* [JP_MedicationDosage_PeriodOfUse]
* [JP_MedicationDosage_RateComment]
* [JP_MedicationDosage_RouteComment]
* [JP_MedicationDosage_SiteComment]
* [JP_MedicationDosage_UsageDuration]

{% include markdown-link-references.md %}