ValueSet: JP_ObservationEndoscopyValueJed_VS
Id: jp-observation-endoscoy-value-jed-vs
Title: "JP Core Observation Endoscopy Value JED ValueSet"
Description: "日本消化器内視鏡学会が推進するJED (Japan Endoscopy Database) Projectのコード値セットのうち主に「所見（存在所見）」「質的診断」に該当するコード"
* ^url = $JP_ObservationEndoscopyValueJed_VS
* ^status = #active
* ^experimental = false
* ^date = "2024-12-30"
* ^copyright = "Copyright JED-Project、JAHIS、日本医療情報学会NeXEHRS課題研究会FHIR日本実装検討WG"

* include codes from system $JP_EndoscopyTerminologyCodesJED_CS

// // =================================================
// // 頭頚部　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20200 "大きさ 長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20301 "[頭頚部 主肉眼型] 0-Ip"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20302 "[頭頚部 主肉眼型] 0-Is"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20303 "[頭頚部 主肉眼型] 0-IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20304 "[頭頚部 主肉眼型] 0-IIb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20305 "[頭頚部 主肉眼型] 0-IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20306 "[頭頚部 主肉眼型] 0-III"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20311 "[頭頚部 主肉眼型] Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20312 "[頭頚部 主肉眼型] Type2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20313 "[頭頚部 主肉眼型] Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20314 "[頭頚部 主肉眼型] Type4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20315 "[頭頚部 主肉眼型] Type5"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20321 "[頭頚部 主肉眼型] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A203ZZ "[頭頚部 主肉眼型] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20401 "[頭頚部 深達度] 上皮内"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20402 "[頭頚部 深達度] 上皮下層"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A20403 "[頭頚部 深達度] 筋層以深"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A204ZZ "[頭頚部 深達度] その他（記述する）"
// // =================================================
// // 食道　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20201 "[周在性] ≤1/4周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20202 "[周在性] 1/4～≤1/2周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20203 "[周在性] 1/2～≤3/4周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20204 "[周在性] 3/4周性～亜全周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20205 "[周在性] 全周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B202ZZ "[周在性] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20301 "[食道 主肉眼型] 0-Ip"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20302 "[食道 主肉眼型] 0-Is"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20303 "[食道 主肉眼型] 0-IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20304 "[食道 主肉眼型] 0-IIb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20305 "[食道 主肉眼型] 0-IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20306 "[食道 主肉眼型] 0-III"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20311 "[食道 主肉眼型] Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20312 "[食道 主肉眼型] Type2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20313 "[食道 主肉眼型] Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20314 "[食道 主肉眼型] Type4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20315 "[食道 主肉眼型] Type5"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20321 "[食道 主肉眼型] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B203ZZ "[食道 主肉眼型] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20401 "[拡大内視鏡所見] A"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20402 "[拡大内視鏡所見] B1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20403 "[拡大内視鏡所見] B2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20404 "[拡大内視鏡所見] B3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20411 "[拡大内視鏡所見] AVA-small"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20412 "[拡大内視鏡所見] AVA-middle"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20413 "[拡大内視鏡所見] AVA-large"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B204ZZ "[拡大内視鏡所見] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20501 "[食道 深達度] EP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20502 "[食道 深達度] LPM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20503 "[食道 深達度] MM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20504 "[食道 深達度] SM1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20505 "[食道 深達度] SM2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20506 "[食道 深達度] SM massive"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20507 "[食道 深達度] EP/LPM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20508 "[食道 深達度] MM/SM1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20509 "[食道 深達度] SM2~"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20510 "[食道 深達度] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20511 "[食道 深達度] AD/AI"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B205ZZ "[食道 深達度] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B20600 "大きさ 長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A201 "[Location] Ls"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A202 "[Location] Lm"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A203 "[Location] Li"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A301 "[Form] F0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A302 "[Form] F1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A303 "[Form] F2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A304 "[Form] F3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A401 "[Color] Cw"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A402 "[Color] Cb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A501 "[Red Color Sign] RC0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A511 "[Red Color Sign] RC1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A512 "[Red Color Sign] RC1 RWM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A513 "[Red Color Sign] RC1 CRS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A514 "[Red Color Sign] RC1 HCS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A521 "[Red Color Sign] RC2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A522 "[Red Color Sign] RC2 RWM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A523 "[Red Color Sign] RC2 CRS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A524 "[Red Color Sign] RC2 HCS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A531 "[Red Color Sign] RC3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A532 "[Red Color Sign] RC3 RWM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A533 "[Red Color Sign] RC3 CRS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A534 "[Red Color Sign] RC3 HCS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A601 "[Telangiectasia] Te0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A602 "[Telangiectasia] Te1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A701 "[Bleeding Sign] gushing bleeding"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A702 "[Bleeding Sign] spurting bleeding"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A703 "[Bleeding Sign] oozing bleeding"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A704 "[Bleeding Sign] red plug"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A705 "[Bleeding Sign] white plug"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A801 "[Mucosal Finding] E"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A802 "[Mucosal Finding] UL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B2A803 "[Mucosal Finding] S"
// // =================================================
// // 胃　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20201 "[胃 主肉眼型] 0-I"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20202 "[胃 主肉眼型] 0-IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20203 "[胃 主肉眼型] 0-IIb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20204 "[胃 主肉眼型] 0-IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20205 "[胃 主肉眼型] 0-III"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20211 "[胃 主肉眼型] Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20212 "[胃 主肉眼型] Type2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20213 "[胃 主肉眼型] Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20214 "[胃 主肉眼型] Type4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20215 "[胃 主肉眼型] Type5"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20221 "[胃 主肉眼型] 隆起"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20222 "[胃 主肉眼型] 陥凹"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20301 "[Ulcer Complication] UL(－)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20302 "[Ulcer Complication] UL(＋)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20401 "[胃 深達度] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20402 "[胃 深達度] SM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20403 "[胃 深達度] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20404 "[胃 深達度] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20405 "[胃 深達度] SE"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20406 "[胃 深達度] SI"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C20500 "大きさ　長径（mm）（記述する）"
// // =================================================
// // 十二指腸　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20201 "[十二指腸 主肉眼型] 隆起"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20202 "[十二指腸 主肉眼型] 陥凹"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20203 "[十二指腸 主肉眼型] 非露出腫瘤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20204 "[十二指腸 主肉眼型] 露出腫瘤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20205 "[十二指腸 主肉眼型] 腫瘤潰瘍型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20206 "[十二指腸 主肉眼型] 潰瘍腫瘤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20207 "[十二指腸 主肉眼型] 潰瘍型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D202ZZ "[十二指腸 主肉眼型] その他の型（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20221 "[十二指腸 主肉眼型] 0-I"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20222 "[十二指腸 主肉眼型] 0-IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20223 "[十二指腸 主肉眼型] 0-IIb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20224 "[十二指腸 主肉眼型] 0-IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20225 "[十二指腸 主肉眼型] 0-III"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20231 "[十二指腸 主肉眼型] Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20232 "[十二指腸 主肉眼型] Type2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20233 "[十二指腸 主肉眼型] Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20234 "[十二指腸 主肉眼型] Type4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20235 "[十二指腸 主肉眼型] Type5"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D20300 "大きさ　長径（mm）（記述する）"
// // =================================================
// // 主乳頭（ERCP）所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20301 "[異常な流出物・内容] 血液"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20302 "[異常な流出物・内容] 膿汁"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20303 "[異常な流出物・内容] ステント"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20304 "[異常な流出物・内容] ドレイン"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20401 "[うっ血] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20402 "[うっ血] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20501 "[裂傷] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20502 "[裂傷] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20601 "[腫瘤] 絨毛状"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20602 "[腫瘤] 腫瘤状"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20603 "[腫瘤] 浸潤性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20604 "[腫瘤] 腫瘤形成性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20605 "[腫瘤] 潰瘍形成性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20701 "[内視鏡処置後] 乳頭括約筋切開"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20702 "[内視鏡処置後] プレカット"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20703 "[内視鏡処置後] 膵管口切開"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20704 "[内視鏡処置後] EPBD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20801 "[腫脹] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20802 "[腫脹] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20901 "[開大] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F20902 "[開大] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21001 "[憩室] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21002 "[憩室] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21101 "[主乳頭 肉眼型] 潜在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21102 "[主乳頭 肉眼型] 結節型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21103 "[主乳頭 肉眼型] 浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21104 "[主乳頭 肉眼型] 嚢胞系"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21105 "[主乳頭 肉眼型] 膵管拡張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21106 "[主乳頭 肉眼型] 混在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21107 "[主乳頭 肉眼型] 分類不能"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F21200 "大きさ　長径（mm）（記述する）"
// // =================================================
// // 主乳頭（ERCP）[膵・胆道内視鏡] 所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4001 "不整粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4002 "乳頭状腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4003 "顆粒"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4004 "蛇行血管"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4005 "血管増生"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4006 "発赤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4007 "瘢痕粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4008 "狭窄と結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA4009 "PTCDチューブ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2FA40ZZ "その他（記述する）"
// // =================================================
// // 副乳頭（ERCP）所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20301 "[異常な流出物・内容] 血液"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20302 "[異常な流出物・内容] 膿汁"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20303 "[異常な流出物・内容] ステント"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20304 "[異常な流出物・内容] ドレイン"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20401 "[うっ血] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20402 "[うっ血] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20501 "[裂傷] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20502 "[裂傷] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20601 "[腫瘤] 絨毛状"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20602 "[腫瘤] 腫瘤状"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20603 "[腫瘤] 浸潤性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20701 "[内視鏡処置後] 乳頭括約筋切開"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20702 "[内視鏡処置後] プレカット"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20801 "[腫脹] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20802 "[腫脹] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20901 "[開大] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G20902 "[開大] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21001 "[憩室] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21002 "[憩室] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21101 "[副乳頭 肉眼型] 潜在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21102 "[副乳頭 肉眼型] 結節型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21103 "[副乳頭 肉眼型] 浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21104 "[副乳頭 肉眼型] 嚢胞系"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21105 "[副乳頭 肉眼型] 膵管拡張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21106 "[副乳頭 肉眼型] 混在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21107 "[副乳頭 肉眼型] 分類不能"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G21200 "大きさ　長径（mm）（記述する）"
// // =================================================
// // 胆道（ERCP）所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20301 "[不整] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20302 "[不整] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20303 "[不整] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20401 "[拡張] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20402 "[拡張] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20403 "[拡張] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20404 "[拡張] 狭窄の前"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20501 "[分枝の減少] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20502 "[分枝の減少] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20503 "[分枝の減少] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20600 "狭窄（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20701 "[結石数] 5個以下(個数を記述する)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20702 "[結石数] 多数"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20800 "結石径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20901 "[壁外性圧迫 狭窄] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20902 "[壁外性圧迫 狭窄] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21001 "[閉塞] 結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21002 "[閉塞] 腫瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21003 "[閉塞] 部分的"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21004 "[閉塞] 完全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H210ZZ "[閉塞] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21101 "[陰影欠損(結石以外)] 気泡"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21102 "[陰影欠損(結石以外)] 胆泥"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21103 "[陰影欠損(結石以外)] 寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21104 "[陰影欠損(結石以外)] Ｔチューブ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21105 "[陰影欠損(結石以外)] ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21106 "[陰影欠損(結石以外)] 腫瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21201 "[ステント] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21202 "[ステント] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21301 "[管外造影] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21302 "[管外造影] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21401 "[嚢胞数] 1個"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21402 "[嚢胞数] 多数"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21500 "嚢胞所見（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21600 "嚢胞　長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21701 "[廔孔] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21702 "[廔孔] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21801 "[手術の既往] 胆嚢摘出術"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21802 "[手術の既往] 総胆管十二指腸吻合術"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21803 "[手術の既往] 総胆管腸管吻合術"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21804 "[手術の既往] 胆嚢腸管吻合術"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21805 "[手術の既往] 肝移植"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21901 "[R-A洞] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H21902 "[R-A洞] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H22001 "[胆嚢管低位分岐] 乳頭からの距離2cm以下"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H22002 "[胆嚢管低位分岐] 乳頭からの距離2cm以上"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H22100 "大きさ　長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H20100 "その他（記述する）"
// // =================================================
// // 胆道（ERCP）肉眼型
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41000 "[胆道 肉眼型] 【胆道癌　腫瘍の肉眼的形態分類】"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41001 "[胆道 肉眼型] 乳頭膨張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41002 "[胆道 肉眼型] 乳頭浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41003 "[胆道 肉眼型] 結節膨張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41004 "[胆道 肉眼型] 結節浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41005 "[胆道 肉眼型] 平坦膨張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41006 "[胆道 肉眼型] 平坦浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41007 "[胆道 肉眼型] 充満型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H41008 "[胆道 肉眼型] 塊状型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42000 "[胆道 肉眼型] 【早期胆道癌の肉眼型分類】"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42001 "[胆道 肉眼型] I 型(隆起型)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42002 "[胆道 肉眼型] Ip型(有茎性)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42003 "[胆道 肉眼型] Is型(無茎性)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42004 "[胆道 肉眼型] II 型(表面型)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42005 "[胆道 肉眼型] IIa型(表面隆起型)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42006 "[胆道 肉眼型] IIb型(表面平坦型)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42007 "[胆道 肉眼型] IIc型(表面陥凹型)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H42008 "[胆道 肉眼型] III 型(陥凹型)"
// // =================================================
// // 胆道（ERCP）深達度
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H51000 "[胆道] 深達度"
// // =================================================
// // 胆道（ERCP）[胆道-膵・胆道内視鏡] 所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4001 "不整粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4002 "乳頭状腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4003 "顆粒"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4004 "蛇行血管"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4005 "血管増生"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4006 "発赤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4007 "瘢痕粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4008 "狭窄と結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4009 "PTCDチューブ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA4010 "NBI所見（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HA40ZZ "その他（記述する）"
// // =================================================
// // 胆道（ERCP）[胆道] ＊超音波所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB10ZZ "超音波的大きさ 長径（ｍｍ）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB20ZZ "超音波的大きさ 短径（ｍｍ）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3001 "[壁構造(中断)] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3002 "[壁構造(中断)] Od"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3003 "[壁構造(中断)] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3004 "[壁構造(中断)] FM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3005 "[壁構造(中断)] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB3006 "[壁構造(中断)] S"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4001 "[壁構造(肥厚)] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4002 "[壁構造(肥厚)] Od"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4003 "[壁構造(肥厚)] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4004 "[壁構造(肥厚)] FM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4005 "[壁構造(肥厚)] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB4006 "[壁構造(肥厚)] S"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB5001 "[形状] 腫瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB50ZZ "[形状] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6001 "[エコーレベル] エコーレベル(正常)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6002 "[エコーレベル] 無エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6003 "[エコーレベル] 低エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6004 "[エコーレベル] 等エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6005 "[エコーレベル] 高エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB6006 "[エコーレベル] Strongエコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB60ZZ "[エコーレベル] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB7001 "[リンパ節] リンパ節(＋)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB7002 "[リンパ節] リンパ節(－)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HB70ZZ "[リンパ節] その他（記述する）"
// // =================================================
// // 膵（ERCP）所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20301 "[膵管非癒合] 完全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20302 "[膵管非癒合] 不完全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20401 "[不整] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20402 "[不整] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20403 "[不整] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20501 "[拡張] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20502 "[拡張] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20503 "[拡張] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20601 "[分枝の減少] 限局性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20602 "[分枝の減少] 区域性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20603 "[分枝の減少] びまん性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20700 "狭窄（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20801 "[閉塞] 結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20802 "[閉塞] 腫瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20803 "[閉塞] 部分的"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20804 "[閉塞] 完全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20901 "[結石数] 5個以下(個数を記述する)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M20902 "[結石数] 多数"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21000 "結石径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21101 "[嚢胞数] 1個"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21102 "[嚢胞数] 多数"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21200 "嚢胞径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21301 "[数珠状] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21302 "[数珠状] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21401 "[管外造影] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21402 "[管外造影] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21501 "[瘻孔] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21502 "[瘻孔] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21601 "[手術の既往] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21602 "[手術の既往] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21701 "[ステント] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21702 "[ステント] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21801 "[粘液貯留] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21802 "[粘液貯留] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21901 "[陰影欠損] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M21902 "[陰影欠損] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22001 "[圧排] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22002 "[圧排] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22101 "[分枝の拡張] あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22102 "[分枝の拡張] なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22201 "[膵 肉眼型] 潜在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22202 "[膵 肉眼型] 結節型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22203 "[膵 肉眼型] 浸潤型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22204 "[膵 肉眼型] 嚢胞系"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22205 "[膵 肉眼型] 膵管拡張型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22206 "[膵 肉眼型] 混在型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22207 "[膵 肉眼型] 分類不能"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M22300 "大きさ　長径（ｍｍ）（記述する）"
// // =================================================
// // 膵（ERCP）深達度予測
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M51000 "[膵] 深達度予測"
// // =================================================
// // 膵（ERCP）[膵-膵・胆道内視鏡] 所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4001 "不整粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4002 "乳頭状腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4003 "顆粒"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4004 "蛇行血管"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4005 "血管増生"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4006 "発赤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4007 "瘢痕粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4008 "狭窄と結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4009 "PTCDチューブ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA4010 "NBI所見（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MA40ZZ "その他（記述する）"
// // =================================================
// // 膵（ERCP）[膵] ＊超音波所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB10ZZ "超音波的大きさ 長径（ｍｍ）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB20ZZ "超音波的大きさ 短径（ｍｍ）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3001 "[壁構造(中断)] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3002 "[壁構造(中断)] Od"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3003 "[壁構造(中断)] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3004 "[壁構造(中断)] FM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3005 "[壁構造(中断)] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB3006 "[壁構造(中断)] S"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4001 "[壁構造(肥厚)] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4002 "[壁構造(肥厚)] Od"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4003 "[壁構造(肥厚)] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4004 "[壁構造(肥厚)] FM"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4005 "[壁構造(肥厚)] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB4006 "[壁構造(肥厚)] S"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB5001 "[形状] 腫瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB5002 "[形状] 単房性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB5003 "[形状] 多房性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB50ZZ "[形状] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6001 "[エコーレベル] エコーレベル(正常)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6002 "[エコーレベル] 無エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6003 "[エコーレベル] 低エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6004 "[エコーレベル] 等エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6005 "[エコーレベル] 高エコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB6006 "[エコーレベル] Strongエコー"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB60ZZ "[エコーレベル] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB7001 "[リンパ節] リンパ節(＋)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB7002 "[リンパ節] リンパ節(－)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MB70ZZ "[リンパ節] その他（記述する）"
// // =================================================
// // 小腸　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20200 "出血"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20300 "狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20400 "腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20500 "潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20600 "瘻孔"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J20100 "その他の局在所見（記述する）"
// // =================================================
// // 大腸　所見
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20201 "[周在性] ≤1/4周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20202 "[周在性] 1/4～≤1/2周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20203 "[周在性] 1/2～≤3/4周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20204 "[周在性] 3/4周性～亜全周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20205 "[周在性] 全周性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L202ZZ "[周在性] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20301 "[大腸 肉眼型1] Is(p)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20302 "[大腸 肉眼型1] Is(p)+IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20303 "[大腸 肉眼型1] Ip"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20304 "[大腸 肉眼型1] Ip+Iic"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20305 "[大腸 肉眼型1] IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20306 "[大腸 肉眼型1] IIa+IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20307 "[大腸 肉眼型1] IIb"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20308 "[大腸 肉眼型1] IIc"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20309 "[大腸 肉眼型1] Is(p)+IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20310 "[大腸 肉眼型1] Ip+IIa"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20321 "[大腸 肉眼型1] Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20322 "[大腸 肉眼型1] Type2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20323 "[大腸 肉眼型1] Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20324 "[大腸 肉眼型1] Type4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20325 "[大腸 肉眼型1] Type5"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20331 "[大腸 肉眼型1] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20341 "[大腸 肉眼型1] SMT"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L203ZZ "[大腸 肉眼型1] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20401 "[大腸 肉眼型2] LST-G"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20402 "[大腸 肉眼型2] LST-NG"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20501 "[Pit診断] Ⅰ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20502 "[Pit診断] Ⅱ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20503 "[Pit診断] ⅢS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20504 "[Pit診断] ⅢL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20505 "[Pit診断] Ⅳ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20507 "[Pit診断] ⅢH"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20508 "[Pit診断] ⅣH"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20509 "[Pit診断] ⅤI 軽度不整（ⅤI non-invasive）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20510 "[Pit診断] ⅤI 高度不整（ⅤI invasive）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20511 "[Pit診断] ⅤN"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20599 "[Pit診断] 判定不能"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20601 "[NBI診断] JNET Type1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20602 "[NBI診断] JNET Type2A"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20603 "[NBI診断] JNET Type2B"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20604 "[NBI診断] JNET Type3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20699 "[NBI診断] 判定不能"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20701 "[内視鏡深達度診断] 腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20711 "[内視鏡深達度診断] M（Tis）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20712 "[内視鏡深達度診断] SM軽度（T1a）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20713 "[内視鏡深達度診断] SM高度（T1b）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20714 "[内視鏡深達度診断] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20715 "[内視鏡深達度診断] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20716 "[内視鏡深達度診断] S(+) A(+)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20800 "大きさ　長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L20900 "切除標本径（ESD症例のみ）長径（mm）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L21000 "切除標本径（ESD症例のみ）短径（mm）（記述する）"
// // =================================================
// // 部位共通 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30001 "異常なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30101 "[化学放射線療法後] CR"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30102 "[化学放射線療法後] nonCR/nonPD 縮小"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30103 "[化学放射線療法後] nonCR/nonPD 不変"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30104 "[化学放射線療法後] nonCR/nonPD 増大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30105 "[化学放射線療法後] PD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30106 "[化学放射線療法後] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30201 "[放射線療法後] CR"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30202 "[放射線療法後] nonCR/nonPD 縮小"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30203 "[放射線療法後] nonCR/nonPD 不変"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30204 "[放射線療法後] nonCR/nonPD 増大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30205 "[放射線療法後] PD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30206 "[放射線療法後] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30301 "[化学療法後] CR"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30302 "[化学療法後] nonCR/nonPD 縮小"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30303 "[化学療法後] nonCR/nonPD 不変"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30304 "[化学療法後] nonCR/nonPD 増大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30305 "[化学療法後] PD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30306 "[化学療法後] 遺残再発"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30401 "[ESD後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30402 "[ESD後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30403 "[ESD後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30404 "[ESD後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30405 "[ESD後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30406 "[ESD後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30407 "[ESD後] 喉頭浮腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30501 "[EMR後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30502 "[EMR後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30503 "[EMR後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30504 "[EMR後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30505 "[EMR後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30506 "[EMR後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30507 "[EMR後] 喉頭浮腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30601 "[APC後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30602 "[APC後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30603 "[APC後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30604 "[APC後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30605 "[APC後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30606 "[APC後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30607 "[APC後] 喉頭浮腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30701 "[ポリペクトミー後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30702 "[ポリペクトミー後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30703 "[ポリペクトミー後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30704 "[ポリペクトミー後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30705 "[ポリペクトミー後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30706 "[ポリペクトミー後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30801 "[腫瘍焼灼術後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30802 "[腫瘍焼灼術後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30803 "[腫瘍焼灼術後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30804 "[腫瘍焼灼術後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30805 "[腫瘍焼灼術後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2Z30806 "[腫瘍焼灼術後] 瘢痕あり"
// // =================================================
// // 頭頚部 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30200 "頭頸部癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30300 "壁内転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30400 "悪性黒色腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30500 "乳頭腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30601 "[粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30602 "[粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30603 "[粘膜下腫瘍] 嚢腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30604 "[粘膜下腫瘍] リンパ管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30605 "[粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30606 "[粘膜下腫瘍] 血管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30607 "[粘膜下腫瘍] 顆粒細胞腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A306ZZ "[粘膜下腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30700 "悪性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30800 "転移性腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30900 "他臓器癌咽喉頭浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31000 "肉芽腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31100 "嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31200 "メラノーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31300 "錯角化"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31400 "炎症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31500 "リンパ濾胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31600 "良性潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31700 "毛細血管拡張症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31801 "[カンジダ症] 軽度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31802 "[カンジダ症] 中等度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31803 "[カンジダ症] 高度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A31900 "廔孔"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32000 "異物"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32100 "裂傷"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32200 "壁外性圧排"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32301 "[経過観察後] 縮小"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32302 "[経過観察後] 不変"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32303 "[経過観察後] 増大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32401 "[ELPS後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32402 "[ELPS後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32403 "[ELPS後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32404 "[ELPS後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32405 "[ELPS後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32406 "[ELPS後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32407 "[ELPS後] 喉頭浮腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32500 "術後吻合部狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32600 "術後縫合不全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32700 "経口的治療後狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32801 "[咽喉食摘術後] 空腸再建"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32802 "[咽喉食摘術後] 胃管再建"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A32900 "喉頭全摘術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A33000 "咽頭部分切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A33100 "喉頭部分切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2A30100 "その他（記述する）"
// // =================================================
// // 食道 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30200 "食道癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30300 "バレット食道腺癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30400 "食道胃接合部腺癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30500 "食道悪性黒色腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30600 "低異型度上皮内腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30700 "ヨード淡染帯"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30801 "[ヨード不染帯] Grade A（ヨード不染色無し）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30802 "[ヨード不染帯] Grade B（A、C以外）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30803 "[ヨード不染帯] Grade C"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B308ZZ "[ヨード不染帯] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30900 "食道癌壁内転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31000 "食道乳頭腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31101 "[食道粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31102 "[食道粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31103 "[食道粘膜下腫瘍] 嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31104 "[食道粘膜下腫瘍] リンパ管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31105 "[食道粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31106 "[食道粘膜下腫瘍] 血管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31107 "[食道粘膜下腫瘍] 顆粒細胞腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B311ZZ "[食道粘膜下腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31200 "食道悪性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31300 "転移性食道腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31400 "他臓器癌食道浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31501 "[逆流性食道炎] Grade N"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31502 "[逆流性食道炎] Grade M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31503 "[逆流性食道炎] Grade A"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31504 "[逆流性食道炎] Grade B"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31505 "[逆流性食道炎] Grade C"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31506 "[逆流性食道炎] Grade D"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31601 "[食道カンジダ症] 軽度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31602 "[食道カンジダ症] 中等度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31603 "[食道カンジダ症] 高度"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31700 "好酸球性食道炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31800 "腐食性食道炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B31900 "結核性食道炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32000 "薬剤性食道炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32102 "[食道裂孔ヘルニア] 傍食道型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32103 "[食道裂孔ヘルニア] 混合型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32104 "[食道裂孔ヘルニア] 滑脱型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32200 "食道静脈瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32301 "[バレット食道] SSBE"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32302 "[バレット食道] LSBE"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32400 "食道アカラシア"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32500 "マロリーワイス症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32600 "良性食道潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32700 "毛細血管拡張症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32800 "食道憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B32900 "良性食道狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33000 "食道ウエブ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33100 "術後吻合部狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33200 "内視鏡治療後狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33300 "孤立性静脈拡張"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33400 "術後縫合不全"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33500 "食道廔孔"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33600 "食道異物"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33700 "食道裂傷"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33800 "食道穿孔"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B33900 "異所性胃粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34000 "壁外性圧排"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34100 "食道ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34200 "食道メラノーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34300 "グリコーゲン・アカントーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34400 "経過観察後（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34600 "POEM後（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34501 "[PDT後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34502 "[PDT後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34503 "[PDT後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34504 "[PDT後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34505 "[PDT後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34506 "[PDT後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34701 "[EVL後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34702 "[EVL後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34703 "[EVL後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34704 "[EVL後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34705 "[EVL後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34706 "[EVL後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34801 "[EIS後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34802 "[EIS後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34803 "[EIS後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34804 "[EIS後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34805 "[EIS後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34806 "[EIS後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34901 "[食道亜全摘後] 胃管再建"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34902 "[食道亜全摘後] 結腸再建"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B34903 "[食道亜全摘後] 空腸再建"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B35000 "咽喉食摘後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B35100 "アカラシア術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2B30100 "その他（記述する）"
// // =================================================
// // 胃 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30200 "腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30300 "胃癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30401 "[胃粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30402 "[胃粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30403 "[胃粘膜下腫瘍] 異所性膵組織"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30404 "[胃粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C304ZZ "[胃粘膜下腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30501 "[胃悪性リンパ腫] DLBCL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30502 "[胃悪性リンパ腫] MALTリンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C305ZZ "[胃悪性リンパ腫] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30600 "胃NET"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30700 "他臓器癌胃転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30800 "他臓器癌胃浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30900 "萎縮性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31000 "表層性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31100 "出血性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31200 "びらん性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31300 "疣状胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31400 "肥厚性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31500 "急性胃粘膜病変(AGML)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31600 "自己免疫性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31700 "鳥肌胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31800 "好酸球性胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C31900 "残胃炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32000 "その他の胃炎（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32100 "腸上皮化生"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32201 "[胃潰瘍] A1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32202 "[胃潰瘍] A2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32211 "[胃潰瘍] H1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32212 "[胃潰瘍] H2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32221 "[胃潰瘍] S1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32222 "[胃潰瘍] S2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32301 "[ポリープ] 過形成性ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32302 "[ポリープ] 胃底腺ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32303 "[ポリープ] ポリポージス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C323ZZ "[ポリープ] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32400 "胃憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32501 "[異物] アニサキス症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32502 "[異物] 胃石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32503 "[異物] 義歯"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C325ZZ "[異物] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32600 "日の丸紅斑、血管拡張症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32700 "胃前庭部毛細血管拡張症（DAVE, GAVE）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32800 "門脈圧亢進性胃症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C32900 "胃静脈瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33000 "マロリーワイス症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33100 "PEG後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33200 "その他の内視鏡治療後（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33300 "HP除菌後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33400 "その他治療後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33500 "PPG後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33600 "DG(Roux-Y)後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33700 "DG(B-I)後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33800 "DG(B-II)後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C33900 "噴門側胃切除後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34000 "胃全摘後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34100 "胃管"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34200 "消化管バイパス術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34300 "胃局所切除後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34400 "PD後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C34500 "PPPD後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2C30100 "その他（記述する）"
// // =================================================
// // 十二指腸 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30200 "十二指腸腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30300 "十二指腸癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30401 "[十二指腸粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30402 "[十二指腸粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30403 "[十二指腸粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D304ZZ "[十二指腸粘膜下腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30501 "[十二指腸悪性リンパ腫] DLBCL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30502 "[十二指腸悪性リンパ腫] 濾胞性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30503 "[十二指腸悪性リンパ腫] MALTリンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D305ZZ "[十二指腸悪性リンパ腫] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30600 "十二指腸NET"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30700 "他臓器癌十二指腸転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30800 "他臓器癌十二指腸浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30900 "十二指腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31001 "[十二指腸潰瘍] A1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31002 "[十二指腸潰瘍] A2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31011 "[十二指腸潰瘍] H1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31012 "[十二指腸潰瘍] H2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31021 "[十二指腸潰瘍] S1stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31022 "[十二指腸潰瘍] S2stage"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31100 "異所性胃粘膜"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31200 "胃上皮化生"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31300 "ブルンネル腺過形成"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31400 "憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31500 "異物"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31600 "血管拡張症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31700 "十二指腸静脈瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31801 "[その他の内視鏡治療後] 出血あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31802 "[その他の内視鏡治療後] 穿孔あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31803 "[その他の内視鏡治療後] 狭窄あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31804 "[その他の内視鏡治療後] 再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31805 "[その他の内視鏡治療後] 潰瘍あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31806 "[その他の内視鏡治療後] 瘢痕あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D31900 "十二指腸術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2D30100 "その他（記述する）"
// // =================================================
// // 主乳頭（ERCP） 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30301 "[造影出来ず] カニュレーション出来ず"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30302 "[造影出来ず] 到達出来ず"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F303ZZ "[造影出来ず] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30400 "乳頭部腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30500 "乳頭部癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30600 "乳頭部腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30701 "[乳頭開大〔Fish mouth〕] IPMNによる"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30702 "[乳頭開大〔Fish mouth〕] IPNBによる"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30801 "[乳頭術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30802 "[乳頭術後] 乳頭形成術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30900 "結石嵌頓"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31000 "良性乳頭狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31100 "乳頭炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31201 "[内視鏡治療後] 切開(EST)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31202 "[内視鏡治療後] 拡張(EPBD)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31203 "[内視鏡治療後] 切除(Papillectomy)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31204 "[内視鏡治療後] 焼灼(APC)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31205 "[内視鏡治療後] ステント"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31301 "[腫脹] 胆管胆石排出後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31400 "乳頭開大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F31500 "ステント"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2F30100 "その他（記述する）"
// // =================================================
// // 副乳頭（ERCP） 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30300 "副乳頭部腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30400 "副乳頭部癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30500 "副乳頭部腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30600 "副乳頭開大〔Fish mouth〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30701 "[副乳頭術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30800 "結石嵌頓"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30900 "良性副乳頭狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31000 "副乳頭炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31101 "[内視鏡治療後] 切開(EST)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31102 "[内視鏡治療後] 拡張(EPBD)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31103 "[内視鏡治療後] 切除(Papillectomy)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31104 "[内視鏡治療後] 焼灼(APC)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31200 "腫脹"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G31300 "副乳頭開大"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2G30100 "その他（記述する）"
// // =================================================
// // 胆道（ERCP） 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30300 "腫瘍性疾患"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30400 "早期胆嚢癌 M-MP癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30500 "進行胆嚢癌 SS癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30600 "進行胆嚢癌 SE癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30700 "進行胆嚢癌 SI癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30800 "コレステロールポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30900 "炎症性ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31000 "線維性ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31100 "肝外胆管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31200 "肝門部胆管癌〔Klatskin腫瘍〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31300 "肝内胆管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31400 "胆管乳頭腺腫症〔Biliary Papillomatosis〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31500 "胆管内乳頭粘液性腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31600 "胆管嚢胞性腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31700 "胆道腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31801 "[悪性胆管狭窄] 膵癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31802 "[悪性胆管狭窄] 胃癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31803 "[悪性胆管狭窄] リンパ節による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31901 "[胆道術後] 胆摘後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31902 "[胆道術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31903 "[胆道術後] 膵体尾部切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31904 "[胆道術後] 肝右葉切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31905 "[胆道術後] 肝左葉切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H31906 "[胆道術後] 胆管空腸吻合術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32000 "正常胆摘後胆道像"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32100 "正常乳頭切開後胆道像"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32200 "肝内結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32300 "総胆管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32401 "[胆嚢結石] 胆嚢内結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32402 "[胆嚢結石] 胆嚢管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32403 "[胆嚢結石] 遺残胆嚢管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32500 "胆泥〔Debris〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32600 "Mirizzi症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32701 "[胆嚢腺筋腫症] びまん型 Diffuse type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32702 "[胆嚢腺筋腫症] 分節型 Segmental type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32703 "[胆嚢腺筋腫症] 底部型 Fundal type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32800 "胆嚢ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H32900 "良性胆管狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33000 "胆管閉塞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33100 "胆管拡張"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33200 "胆汁漏出"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33300 "胆管瘻"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33400 "Sump症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33501 "[膵胆管合流異常] 胆管合流型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33502 "[膵胆管合流異常] 膵管合流型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33601 "[総胆管嚢腫] Alonso-Lej I 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33602 "[総胆管嚢腫] Alonso-Lej II 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33611 "[総胆管嚢腫] 総胆管瘤 Alonso-Lej III 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33621 "[総胆管嚢腫] 戸谷 I 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33622 "[総胆管嚢腫] 戸谷 II 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33623 "[総胆管嚢腫] 戸谷 III 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33624 "[総胆管嚢腫] 戸谷 IV 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33700 "Caroli病"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33800 "硬化性胆管炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H33900 "化膿性胆管炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H34000 "肝硬変"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H34100 "血液胆汁"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H34200 "寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2H30100 "その他（記述する）"
// // =================================================
// // 胆道（ERCP）超音波診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0300 "胆道病変描出出来ず"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0401 "早期胆嚢癌 M-MP癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0402 "進行胆嚢癌 SS癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0403 "進行胆嚢癌 SE癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0404 "進行胆嚢癌 SI癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0500 "胆嚢腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0601 "コレステロールポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0602 "炎症性ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0603 "線維性ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0700 "肝外胆管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0800 "肝門部胆管癌〔Klatskin腫瘍〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0900 "肝内胆管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1000 "胆管乳頭腺腫症〔Biliary Papillomatosis〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1100 "胆管内乳頭粘液性腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1200 "胆管嚢胞性腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1301 "肝外胆管腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1302 "肝内胆管腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1401 "[悪性胆管狭窄] 膵癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1402 "[悪性胆管狭窄] 胃癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1403 "[悪性胆管狭窄] リンパ節による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1501 "[胆道術後] 胆摘後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1502 "[胆道術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1503 "[胆道術後] 膵体尾部切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1504 "[胆道術後] 肝右葉切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1505 "[胆道術後] 肝左葉切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1506 "[胆道術後] 胆管空腸吻合術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1600 "肝内結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1700 "総胆管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1801 "[胆嚢結石] 胆嚢内結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1802 "[胆嚢結石] 胆嚢管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1803 "[胆嚢結石] 遺残胆嚢管結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC1900 "胆泥〔Debris〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2000 "Mirizzi症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2101 "[胆嚢腺筋腫症] びまん型 Diffuse type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2102 "[胆嚢腺筋腫症] 分節型 Segmental type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2103 "[胆嚢腺筋腫症] 底部型 Fundal type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2200 "胆嚢ポリープ"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2300 "良性胆管狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2400 "胆管閉塞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2500 "胆管拡張"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2600 "胆管瘻"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2700 "Sump症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2801 "[膵胆管合流異常] 胆管合流型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2802 "[膵胆管合流異常] 膵管合流型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2901 "[総胆管嚢腫] Alonso-Lej I 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2902 "[総胆管嚢腫] Alonso-Lej II 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2911 "[総胆管嚢腫] 総胆管瘤 Alonso-Lej III 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2921 "[総胆管嚢腫] 戸谷 I 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2922 "[総胆管嚢腫] 戸谷 II 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2923 "[総胆管嚢腫] 戸谷 III 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC2924 "[総胆管嚢腫] 戸谷 IV 型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC3000 "Caroli病"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC3100 "硬化性胆管炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC3200 "化膿性胆管炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC3300 "寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HC0100 "その他（記述する）"
// // =================================================
// // 胆道（ERCP）超音波進展度診断－癌進展度診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1101 "[壁深達度] M"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1102 "[壁深達度] FM(胆管癌)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1103 "[壁深達度] MP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1104 "[壁深達度] SS"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1105 "[壁深達度] SE"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1106 "[壁深達度] SI"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1201 "S0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1202 "S1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1203 "S2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1204 "S3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1205 "SX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1301 "Hinf0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1302 "Hinf1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1303 "Hinf2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1304 "Hinf3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1305 "HinfX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1401 "H0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1402 "H1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1403 "H2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1404 "H3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1405 "HX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1501 "Binf(胆嚢癌)0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1502 "Binf(胆嚢癌)1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1503 "Binf(胆嚢癌)2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1504 "Binf(胆嚢癌)3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1505 "Binf(胆嚢癌)X"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1601 "Ginf(胆管癌)0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1602 "Ginf(胆管癌)1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1603 "Ginf(胆管癌)2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1604 "Ginf(胆管癌)3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1605 "Ginf(胆管癌)X"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1701 "Panc(胆管癌)0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1702 "Panc(胆管癌)1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1703 "Panc(胆管癌)2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1704 "Panc(胆管癌)3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1705 "Panc(胆管癌)X"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1801 "Du(胆管癌)0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1802 "Du(胆管癌)1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1803 "Du(胆管癌)2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1804 "Du(胆管癌)3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1805 "Du(胆管癌)X"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1901 "PV0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1902 "PV1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1903 "PV2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1904 "PV3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1905 "PVX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1A01 "A0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1A02 "A1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1A03 "A2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1A04 "A3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1A05 "AX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1B01 "P0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1B02 "P1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1B03 "P2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1B04 "P3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1B05 "PX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1C01 "N0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1C02 "N1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1C03 "N2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1C04 "N3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2HD1C05 "NX"
// // =================================================
// // 膵（ERCP） 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30301 "[膵癌] 通常型膵管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30302 "[膵癌] 退形成性膵管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30401 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 主膵管型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30402 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 分枝型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30403 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 混合型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30501 "[粘液性嚢胞腫瘍〔MCN〕] 粘液性嚢胞腺腫,MCA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30502 "[粘液性嚢胞腫瘍〔MCN〕] 粘液性嚢胞腺癌,MCC"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30601 "[漿液性嚢胞腫瘍〔SCN〕] 漿液性嚢胞腺腫,SCA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30602 "[漿液性嚢胞腫瘍〔SCN〕] 漿液性嚢胞腺癌,SCC"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30700 "膵腺房細胞癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30801 "[膵内分泌腫瘍] カルチノイド腫瘍 G1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30802 "[膵内分泌腫瘍] PDNET G2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30803 "[膵内分泌腫瘍] 膵内分泌癌 PDNEC G3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30900 "Solid-pseudopapillary腫瘍〔SPN〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31000 "膵悪性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31101 "[転移性膵腫瘍] 腎癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31102 "[転移性膵腫瘍] 大腸癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31201 "[悪性膵管狭窄] 腎癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31202 "[悪性膵管狭窄] 大腸癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31301 "[その他の膵腫瘍] リンパ上皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31302 "[その他の膵腫瘍] 類表皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31303 "[その他の膵腫瘍] 類皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31401 "[膵術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31402 "[膵術後] 膵体尾部切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31403 "[膵術後] 膵分節切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31404 "[膵術後] 膵腫瘍核出術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31405 "[膵術後] 膵仮性嚢胞・膿瘍ドレナージ術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31501 "[慢性膵炎] 膵石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31502 "[慢性膵炎] 遺伝性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31600 "腫瘤形成性膵炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31700 "自己免疫性膵炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31800 "仮性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31901 "[良性膵管狭窄] 結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M31902 "[良性膵管狭窄] 術後狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32000 "単純性膵管拡張"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32100 "単純性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32200 "その他の非腫瘍性嚢胞（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32301 "[膵管癒合不全] 完全型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32302 "[膵管癒合不全] 不完全型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32400 "輪状膵"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M32500 "寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2M30100 "その他（記述する）"
// // =================================================
// // 膵（ERCP）超音波診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0200 "異常所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0300 "膵病変描出出来ず"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0401 "[膵癌] 通常型膵管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0402 "[膵癌] 退形成性膵管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0501 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 主膵管型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0502 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 分枝型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0503 "[膵管内乳頭粘液性腫瘍〔IPMN〕] 混合型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0601 "[粘液性嚢胞腫瘍〔MCN〕] 粘液性嚢胞腺腫,MCA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0602 "[粘液性嚢胞腫瘍〔MCN〕] 粘液性嚢胞腺癌,MCC"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0701 "[漿液性嚢胞腫瘍〔SCN〕] 漿液性嚢胞腺腫,SCA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0702 "[漿液性嚢胞腫瘍〔SCN〕] 漿液性嚢胞腺癌,SCC"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0800 "膵腺房細胞癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0901 "[膵内分泌腫瘍] カルチノイド腫瘍 G1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0902 "[膵内分泌腫瘍] PDNET G2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0903 "[膵内分泌腫瘍] 膵内分泌癌 PDNEC G3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1000 "Solid-pseudopapillary腫瘍〔SPN〕"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1100 "膵悪性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1201 "[転移性膵腫瘍] 腎癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1202 "[転移性膵腫瘍] 大腸癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1301 "[悪性膵管狭窄] 腎癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1302 "[悪性膵管狭窄] 大腸癌による"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1401 "[その他の膵腫瘍] リンパ上皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1402 "[その他の膵腫瘍] 類表皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1403 "[その他の膵腫瘍] 類皮嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1501 "[膵術後] 膵頭十二指腸切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1502 "[膵術後] 膵体尾部切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1503 "[膵術後] 膵分節切除術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1504 "[膵術後] 膵腫瘍核出術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1505 "[膵術後] 膵仮性嚢胞・膿瘍ドレナージ術後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1601 "[慢性膵炎] 膵石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1602 "[慢性膵炎] 遺伝性"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1700 "腫瘤形成性膵炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1800 "自己免疫性膵炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC1900 "仮性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2001 "[良性膵管狭窄] 結石"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2002 "[良性膵管狭窄] 術後狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2100 "単純性膵管拡張"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2200 "単純性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2300 "その他の非腫瘍性嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2401 "[膵管癒合不全] 完全型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2402 "[膵管癒合不全] 不完全型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2500 "輪状膵"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2600 "寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC2701 "[内視鏡治療後] ステント挿入後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MC0100 "その他（記述する）"
// // =================================================
// // 膵（ERCP）超音波進展度診断－癌進展度診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1101 "TS1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1102 "TS2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1103 "TS3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1104 "TS4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1105 "TSX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1201 "Tis"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1202 "T1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1203 "T2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1204 "T3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1205 "T4"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1206 "TX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1301 "CH－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1302 "CH＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1303 "CHX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1401 "DU－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1402 "DU＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1403 "DUX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1501 "S－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1502 "S＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1503 "SX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1601 "RP－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1602 "RP＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1603 "RPX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1701 "PV－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1702 "PV＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1703 "PVX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1801 "A－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1802 "A＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1803 "AX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1901 "PL－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1902 "PL＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1903 "PLX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1A01 "OO－"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1A02 "OO＋"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1A03 "OOX"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1B01 "N0"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1B02 "N1"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1B03 "N2"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1B04 "N3"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2MD1B05 "NX"
// // =================================================
// // 小腸 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30200 "特記所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30301 "[上皮性腫瘍] 腺腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30302 "[上皮性腫瘍] 癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30303 "[上皮性腫瘍] 神経内分泌腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J303ZZ "[上皮性腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30401 "[ポリポーシス] 家族性大腸腺腫症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30402 "[ポリポーシス] Peutz-Jeghers症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30403 "[ポリポーシス] Cronkhite-Canada症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30404 "[ポリポーシス] Cowden病"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J304ZZ "[ポリポーシス] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30501 "[悪性リンパ腫] 濾胞性リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30502 "[悪性リンパ腫] DLBCL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30503 "[悪性リンパ腫] T細胞リンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J305ZZ "[悪性リンパ腫] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30601 "[粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30602 "[粘膜下腫瘍] 平滑筋肉腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30603 "[粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30604 "[粘膜下腫瘍] 嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30605 "[粘膜下腫瘍] 異所性膵組織"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30606 "[粘膜下腫瘍] リンパ管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30607 "[粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30608 "[粘膜下腫瘍] 血管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30609 "[粘膜下腫瘍] 神経鞘腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30610 "[粘膜下腫瘍] 悪性神経鞘腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J306ZZ "[粘膜下腫瘍] その他の粘膜下腫瘍（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30701 "[転移性腫瘍] 他臓器癌転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30702 "[転移性腫瘍] 他臓器癌直接浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30801 "[その他の腫瘍] 悪性黒色腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30802 "[その他の腫瘍] 形質細胞腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30803 "[その他の腫瘍] カポジ肉腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30804 "[その他の腫瘍] その他の腫瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30901 "[治療後評価] CRT後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30902 "[治療後評価] RT後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30903 "[治療後評価] Chemotherapy後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30904 "[治療後評価] 無治療経過観察後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31001 "[内視鏡治療後評価] 内視鏡治療後"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31101 "[炎症] クローン病"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31102 "[炎症] ベーチェット病・単純性潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31103 "[炎症] 非特異性多発性小腸潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31104 "[炎症] 好酸球性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31105 "[炎症] 薬剤性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31106 "[炎症] 放射線性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31107 "[炎症] 感染性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31108 "[炎症] 腸結核"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31109 "[炎症] GVHD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31110 "[炎症] TMA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31111 "[炎症] 非特異性小腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J311ZZ "[炎症] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31201 "[血管性病変] 血管拡張症（矢野山本１a）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31202 "[血管性病変] 血管拡張症（矢野山本１b）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31203 "[血管性病変] デュラホイ病変（矢野山本2a）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31204 "[血管性病変] デュラホイ病変（矢野山本2b）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31205 "[血管性病変] 動静脈奇形（矢野山本3）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J312ZZ "[血管性病変] その他（矢野山本4）（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J31206 "[血管性病変] 静脈瘤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30101 "[その他] 憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30102 "[その他] メッケル憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30103 "[その他] 寄生虫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30104 "[その他] アミロイドーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30105 "[その他] サルコイドーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J30106 "[その他] 全身性疾患に伴うもの"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2J301ZZ "[その他] その他（記述する）"
// // =================================================
// // 大腸 質的診断
// // =================================================
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30200 "特記所見なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30301 "[腫瘍] 腺腫・早期大腸癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30311 "[腫瘍] 進行大腸癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30401 "[鋸歯状病変] HP"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30402 "[鋸歯状病変] SSA/P"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30403 "[鋸歯状病変] TSA"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30404 "[鋸歯状病変] Mixed type"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30501 "[悪性リンパ腫] MALTリンパ腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30502 "[悪性リンパ腫] DLBCL"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L305ZZ "[悪性リンパ腫] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30601 "[粘膜下腫瘍] 平滑筋腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30602 "[粘膜下腫瘍] 平滑筋肉腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30603 "[粘膜下腫瘍] GIST"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30604 "[粘膜下腫瘍] 嚢胞"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30605 "[粘膜下腫瘍] リンパ管腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30606 "[粘膜下腫瘍] 脂肪腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30607 "[粘膜下腫瘍] カルチノイド"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L306ZZ "[粘膜下腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30701 "[転移性腫瘍] 他臓器癌転移"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30702 "[転移性腫瘍] 他臓器癌直接浸潤"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30801 "[その他の腫瘍] 悪性黒色腫"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30802 "[その他の腫瘍] 肛門管癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30803 "[その他の腫瘍] 神経内分泌癌"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L308ZZ "[その他の腫瘍] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30901 "[内視鏡治療後] 遺残再発あり"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30902 "[内視鏡治療後] 遺残再発なし"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L309ZZ "[内視鏡治療後] その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31001 "[局所切除後（外科手術）] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31002 "[局所切除後（外科手術）] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31011 "[局所切除後（外科手術）] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31012 "[局所切除後（外科手術）] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31101 "[回盲部切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31102 "[回盲部切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31111 "[回盲部切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31112 "[回盲部切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31201 "[右半結腸切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31202 "[右半結腸切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31211 "[右半結腸切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31212 "[右半結腸切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31301 "[横行結腸切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31302 "[横行結腸切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31311 "[横行結腸切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31312 "[横行結腸切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31401 "[左半結腸切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31402 "[左半結腸切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31411 "[左半結腸切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31412 "[左半結腸切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31501 "[下行結腸切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31502 "[下行結腸切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31511 "[下行結腸切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31512 "[下行結腸切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31601 "[S状結腸切除後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31602 "[S状結腸切除後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31611 "[S状結腸切除後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31612 "[S状結腸切除後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31701 "[HAR後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31702 "[HAR後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31711 "[HAR後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31712 "[HAR後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31801 "[LAR後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31802 "[LAR後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31811 "[LAR後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31812 "[LAR後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31901 "[Miles’ope後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31902 "[Miles’ope後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31911 "[Miles’ope後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L31912 "[Miles’ope後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32001 "[FAP術後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32002 "[FAP術後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32011 "[FAP術後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32012 "[FAP術後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32101 "[Hartmann手術後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32102 "[Hartmann手術後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32111 "[Hartmann手術後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32112 "[Hartmann手術後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32201 "[大腸全摘後] 吻合部再発：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32202 "[大腸全摘後] 吻合部再発：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32211 "[大腸全摘後] 吻合部狭窄：有"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32212 "[大腸全摘後] 吻合部狭窄：無"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32301 "[家族性大腸腺腫症（FAP)] 密生型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32302 "[家族性大腸腺腫症（FAP)] 非密生型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32400 "Gardner症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32500 "Cronkhite-Canada症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32600 "Peutz-Jeghers症候群"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32700 "若年性ポリポーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32801 "[Serrated polyposis syndrome（SPS）] 10mm以上が2個以上"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32802 "[Serrated polyposis syndrome（SPS）] 20個以上"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L30100 "その他（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32901 "[潰瘍性大腸炎] 直腸炎型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32902 "[潰瘍性大腸炎] 左側大腸炎型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32903 "[潰瘍性大腸炎] 全大腸炎型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L32904 "[潰瘍性大腸炎] 右側型（分節型）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33001 "[Crohn病] 大腸型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33002 "[Crohn病] 小腸大腸型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33003 "[Crohn病] 小腸型"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33100 "虚血性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33200 "放射線性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33300 "出血性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33400 "偽膜性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33500 "病原性大腸菌腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33600 "アフタ様大腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33700 "腸管ベーチェット"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33800 "単純性潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L33900 "感染性腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34000 "アメーバ腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34100 "腸結核"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34200 "GVHD"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34300 "サイトメガロ腸炎"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34400 "憩室"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34500 "痔核"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34600 "偽メラノーシス"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34700 "直腸潰瘍"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34800 "粘膜逸脱症候群（MPS)"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L34900 "腸管嚢胞性気腫症"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35000 "腸捻転"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35100 "内視鏡治療後出血"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35200 "憩室出血"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35300 "その他の出血（記述する）"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35400 "IBDに伴う狭窄"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35500 "collagenous colitis"
// * $JP_EndoscopyTerminologyCodesJED_CS#Z2L35600 "その他の非腫瘍性病変（記述する）"