name: JPCore FHIR main Task
on:
  push:
    branches:
      - 'main'
      - 'hotfix/**'
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - '.github/workflows/main.yaml'
      - '.github/workflows/_build.yaml'
  pull_request:
    branches:
      - 'main'
jobs:
  call-build:
    uses: ./.github/workflows/_build.yaml
    with:
      release-version: '1.3.0-dev'
      ig-publisher-tag: 'latest'
      upload-packages: true
    secrets: inherit
